import { Link } from "react-router-dom";
import "../../index.css";

const imgChatGptImage1 = "/assets/emdad/dashboard/logo.png";
const imgSuccessIcon = "/assets/emdad/release-success/success-icon.svg";
const imgEllipse = "/assets/emdad/release-success/step-circle.svg";
const imgGroup = "/assets/emdad/dashboard/group.svg";
const imgGroup1 = "/assets/emdad/dashboard/group1.svg";
const imgCertificateIcon = "/assets/emdad/dashboard/certificate-icon.svg";
const imgFundSynergyIcon = "/assets/emdad/dashboard/fund-synergy-icon.svg";
const imgGroup2 = "/assets/emdad/dashboard/group2.svg";
const imgGroup3 = "/assets/emdad/dashboard/group3.svg";
const imgGroup4 = "/assets/emdad/dashboard/group4.svg";

export default function EmdadReleaseSuccess() {
  return (
    <div className="emdad-panel bg-[#f5f8fb] relative w-full h-full" data-node-id="2143:2" data-name="emdad-release-success">
      <div className="absolute bg-[#f5f8fb] content-stretch flex flex-col gap-[16px] h-[900px] items-start left-0 overflow-clip px-[28px] py-[22px] top-0 w-[1216px]" data-node-id="2143:3" data-name="Main Content">
        <div className="[word-break:break-word] bg-white h-[64px] leading-[0] overflow-clip relative rounded-[12px] shrink-0 text-right w-full" data-node-id="2143:125" data-name="header">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[30px] justify-center left-[1132px] text-[#17324d] text-[22px] top-[19px] w-[1104px]" data-node-id="2143:126"><p className="leading-[normal]" dir="auto">آزادسازی وجه با موفقیت ثبت شد</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[1132px] text-[#60758a] text-[11px] top-[46px] w-[1104px]" data-node-id="2143:127"><p className="leading-[normal]" dir="auto">نتیجه اقدام کمیته امداد برای مرحله تأییدشده پروژه</p></div>
        </div>
        <div className="bg-[#e9f8f1] border border-[#cdeedf] border-solid h-[154px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2143:128" data-name="release-success-hero">
          <div className="absolute left-[1065px] w-[54px] h-[54px] top-[34px]" data-node-id="2143:129" data-name="success-icon"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgSuccessIcon} /></div>
          <div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[40px] justify-center leading-[0] left-[1092px] text-[28px] text-center text-white top-[59px] w-[36px]" data-node-id="2143:130"><p className="leading-[normal]">✓</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[30px] justify-center leading-[0] left-[1035px] text-[#17324d] text-[18px] text-right top-[42px] w-[1008px]" data-node-id="2143:131"><p className="leading-[normal]" dir="auto">آزادسازی وجه مرحله ثبت شد</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[24px] justify-center leading-[0] left-[1035px] text-[#60758a] text-[11px] text-right top-[73px] w-[1008px]" data-node-id="2143:132"><p className="leading-[normal]" dir="auto">درخواست این مرحله با موفقیت بسته شد و نتیجه آزادسازی در سوابق پرداخت کمیته امداد ثبت گردید.</p></div>
          <div className="absolute bg-[#ddf4e8] h-[30px] left-[27px] overflow-clip rounded-[15px] top-[101px] w-[120px]" data-node-id="2143:133" data-name="status-badge"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[60px] text-[#159455] text-[11px] text-center top-[15px] w-[104px]" data-node-id="2143:134"><p className="leading-[normal]" dir="auto">تکمیل‌شده</p></div></div>
        </div>
        <div className="[word-break:break-word] bg-white border border-[#e4ebf1] border-solid h-[194px] leading-[0] overflow-clip relative rounded-[12px] shrink-0 text-right w-full" data-node-id="2143:135" data-name="release-result-summary">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[1139px] text-[#17324d] text-[16px] top-[27px] w-[1120px]" data-node-id="2143:136"><p className="leading-[normal]" dir="auto">خلاصه درخواست</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[1139px] text-[#60758a] text-[10px] top-[52px] w-[1120px]" data-node-id="2143:137"><p className="leading-[normal]" dir="auto">اطلاعات پروژه و مرحله‌ای که آزادسازی آن انجام شده است</p></div>
          <div className="absolute bg-[#f8fafc] h-[84px] left-[889px] overflow-clip rounded-[10px] top-[81px] w-[250px]" data-node-id="2143:138" data-name="summary-item"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[236px] text-[#60758a] text-[10px] top-[20px] w-[222px]" data-node-id="2143:139"><p className="leading-[normal]" dir="auto">پروژه</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[34px] justify-center left-[236px] text-[#17324d] text-[12px] top-[51px] w-[222px]" data-node-id="2143:140"><p className="leading-[normal]" dir="auto">اشتغال زنان روستایی</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[84px] left-[599px] overflow-clip rounded-[10px] top-[81px] w-[250px]" data-node-id="2143:141" data-name="summary-item"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[236px] text-[#60758a] text-[10px] top-[20px] w-[222px]" data-node-id="2143:142"><p className="leading-[normal]" dir="auto">مرحله</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[34px] justify-center left-[236px] text-[#17324d] text-[12px] top-[51px] w-[222px]" data-node-id="2143:143"><p className="leading-[normal]" dir="auto">شناسایی و ارزیابی</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[84px] left-[309px] overflow-clip rounded-[10px] top-[81px] w-[250px]" data-node-id="2143:144" data-name="summary-item"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[236px] text-[#60758a] text-[10px] top-[20px] w-[222px]" data-node-id="2143:145"><p className="leading-[normal]" dir="auto">سهم مرحله</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[34px] justify-center left-[236px] text-[#17324d] text-[12px] top-[51px] w-[222px]" data-node-id="2143:146"><p className="leading-[normal]">۲۰٪</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[84px] left-[19px] overflow-clip rounded-[10px] top-[81px] w-[250px]" data-node-id="2143:147" data-name="summary-item"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[236px] text-[#60758a] text-[10px] top-[20px] w-[222px]" data-node-id="2143:148"><p className="leading-[normal]" dir="auto">ارزیابی آینه</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[34px] justify-center left-[236px] text-[#159455] text-[12px] top-[51px] w-[222px]" data-node-id="2143:149"><p className="leading-[normal]" dir="auto">تأیید شده</p></div></div>
        </div>
        <div className="bg-white border border-[#e4ebf1] border-solid h-[174px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2143:150" data-name="release-process-result">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[1139px] text-[#17324d] text-[16px] text-right top-[27px] w-[1120px]" data-node-id="2143:151"><p className="leading-[normal]" dir="auto">وضعیت فرایند</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[1139px] text-[#60758a] text-[10px] text-right top-[52px] w-[1120px]" data-node-id="2143:152"><p className="leading-[normal]" dir="auto">این درخواست تمام مراحل لازم برای آزادسازی را طی کرده است</p></div>
          <div className="absolute bg-[#f8fafc] h-[68px] left-[789px] overflow-clip rounded-[10px] top-[81px] w-[340px]" data-node-id="2143:153" data-name="completed-step"><div className="absolute left-[286px] w-[32px] h-[32px] top-[18px]" data-node-id="2143:154" data-name="Ellipse"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgEllipse} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[302px] w-[24px] h-[24px] text-[11px] text-center text-white top-[33px]" data-node-id="2143:155"><p className="leading-[normal]">۱</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[32px] justify-center leading-[0] left-[272px] text-[#17324d] text-[11px] text-right top-[33px] w-[258px]" data-node-id="2143:156"><p className="leading-[normal]" dir="auto">تأیید مرحله توسط آینه</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[68px] left-[409px] overflow-clip rounded-[10px] top-[81px] w-[340px]" data-node-id="2143:157" data-name="completed-step"><div className="absolute left-[286px] w-[32px] h-[32px] top-[18px]" data-node-id="2143:158" data-name="Ellipse"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgEllipse} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[302px] w-[24px] h-[24px] text-[11px] text-center text-white top-[33px]" data-node-id="2143:159"><p className="leading-[normal]">۲</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[32px] justify-center leading-[0] left-[272px] text-[#17324d] text-[11px] text-right top-[33px] w-[258px]" data-node-id="2143:160"><p className="leading-[normal]" dir="auto">ثبت آزادسازی توسط کمیته امداد</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[68px] left-[29px] overflow-clip rounded-[10px] top-[81px] w-[340px]" data-node-id="2143:161" data-name="completed-step"><div className="absolute left-[286px] w-[32px] h-[32px] top-[18px]" data-node-id="2143:162" data-name="Ellipse"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgEllipse} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[302px] w-[24px] h-[24px] text-[11px] text-center text-white top-[33px]" data-node-id="2143:163"><p className="leading-[normal]">۳</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[32px] justify-center leading-[0] left-[272px] text-[#17324d] text-[11px] text-right top-[33px] w-[258px]" data-node-id="2143:164"><p className="leading-[normal]" dir="auto">ثبت نتیجه در سوابق پرداخت</p></div></div>
        </div>
        <div className="bg-white border border-[#e4ebf1] border-solid h-[146px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2143:165" data-name="success-actions">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[1139px] text-[#17324d] text-[13px] text-right top-[29px] w-[1120px]" data-node-id="2143:166"><p className="leading-[normal]" dir="auto">درخواست بسته شد</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[22px] justify-center leading-[0] left-[1139px] text-[#60758a] text-[10px] text-right top-[56px] w-[1120px]" data-node-id="2143:167"><p className="leading-[normal]" dir="auto">این مرحله دیگر در صف درخواست‌های آزادسازی قرار نمی‌گیرد و نتیجه آن از سوابق پرداخت قابل پیگیری است.</p></div>
          <Link to="/panel/emdad/payment-history" className="absolute bg-[#2094e3] block cursor-pointer h-[42px] left-[19px] overflow-clip rounded-[9px] top-[85px] w-[190px]" data-node-id="2143:168" data-name="view-payment-history"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[95px] text-[11px] text-center text-white top-[21px] w-[170px]" data-node-id="2143:169"><p className="leading-[normal]" dir="auto">مشاهده سوابق پرداخت</p></div></Link>
          <Link to="/panel/emdad/release-requests" className="absolute bg-white block border border-[#d9e3ec] border-solid cursor-pointer h-[42px] left-[221px] overflow-clip rounded-[9px] top-[85px] w-[190px]" data-node-id="2143:170" data-name="back-to-release-requests"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[94px] text-[#17324d] text-[11px] text-center top-[20px] w-[170px]" data-node-id="2143:171"><p className="leading-[normal]" dir="auto">بازگشت به درخواست‌ها</p></div></Link>
        </div>
      </div>
      <div className="absolute bg-[#17324d] content-stretch flex flex-col gap-[10px] h-[900px] items-end left-[1216px] pb-[18px] pt-[20px] px-[16px] top-0 w-[224px]" data-node-id="2143:63" data-name="colored-sidebar">
        <div className="bg-white content-stretch flex h-[56px] items-center justify-end overflow-clip px-[10px] py-[8px] relative rounded-[12px] shrink-0 w-[192px]" data-node-id="2143:64" data-name="brand-logo"><div className="h-[40px] relative shrink-0 w-[118px]" data-node-id="2143:65" data-name="ChatGPT Image ۲۹ مرداد ۱۴۰۵، ۱۵_۱۶_۳۵ 1"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="" className="absolute h-full left-[5.28%] max-w-none top-0 w-[100.73%]" src={imgChatGptImage1} /></div></div></div>
        <div className="[word-break:break-word] content-stretch flex flex-col gap-[3px] h-[64px] items-start justify-end overflow-clip px-[8px] py-[7px] relative shrink-0 text-center w-[192px]" data-node-id="2143:66" data-name="panel-identity"><p className="font-sans font-medium h-[24px] leading-[normal] relative shrink-0 text-[13px] text-white w-[176px]" dir="auto" data-node-id="2143:67">سامانه ماه</p><div className="flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] relative shrink-0 text-[#d8e7f3] text-[10px] w-[176px]" data-node-id="2143:68"><p className="leading-[normal]" dir="auto">پنل کمیته امداد</p></div></div>
        <Link to="/panel/emdad" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2143:69" data-name="dashboard-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2143:70">داشبورد</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2143:71" data-name="dashboard-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2143:72" data-name="Frame"><div className="absolute inset-[11.11%]" data-node-id="2143:73" data-name="Group"><div className="absolute inset-[-5.71%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup} /></div></div></div></div></Link>
        <Link to="/panel/emdad/release-requests" className="bg-[#2094e3] content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2143:78" data-name="release-requests-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2143:79">درخواست‌های آزادسازی</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2143:80" data-name="users-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2143:81" data-name="Frame"><div className="absolute inset-[22.22%_13.89%_19.44%_13.89%]" data-node-id="2143:82" data-name="Group"><div className="absolute inset-[-7.62%_-6.15%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup1} /></div></div></div></div></Link>
        <Link to="/panel/emdad/article-172-approvals" className="block cursor-pointer h-[38px] overflow-clip relative rounded-[8px] shrink-0 w-[192px]" data-node-id="2143:85" data-name="article-172-approvals-nav"><p className="-translate-x-full [word-break:break-word] absolute font-sans font-normal leading-[normal] left-[152px] text-[#edf5fc] text-[12px] text-right top-[9.5px] w-[142px]" dir="auto" data-node-id="2143:86">تأیید گواهی ماده ۱۷۲</p><div className="absolute left-[162px] w-[18px] h-[18px] top-[10px]" data-node-id="2143:87" data-name="certificate-icon"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgCertificateIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2223:29" data-name="fund-synergy-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2223:30">هم‌افزایی صندوق</p><div className="relative shrink-0 w-[18px] h-[18px]" data-node-id="2226:20" data-name="fund-synergy-icon"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgFundSynergyIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy/history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2237:187" data-name="fund-synergy-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2237:188">سوابق هم‌افزایی صندوق</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2237:189" data-name="project-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2237:190" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2237:191" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/payment-history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2143:91" data-name="payment-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2143:92">سوابق پرداخت</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2143:93" data-name="project-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2143:94" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2143:95" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/financial-reports" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2143:99" data-name="financial-reports-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2143:100">گزارش‌های مالی</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2143:101" data-name="milestone-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2143:102" data-name="Frame"><div className="absolute inset-[13.89%_11.11%]" data-node-id="2143:103" data-name="Group"><div className="absolute inset-[-6.15%_-5.71%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup3} /></div></div></div></div></Link>
        <Link to="/panel/emdad/fund-returns" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2382:422" data-name="fund-returns-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2382:423">منابع برگشتی صندوق</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2382:424" data-name="project-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2382:425" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2382:426" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup2} /></div></div></div></div></Link>
        <div className="flex-[1_0_0] min-h-px relative w-[192px]" data-node-id="2143:116" data-name="sidebar-spacer" />
        <button type="button" className="bg-white content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end opacity-[0.96] overflow-clip px-[12px] relative rounded-[9px] shrink-0 w-[192px]" data-node-id="2143:117" data-name="logout-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[#17324d] text-[12px] text-right w-[142px]" dir="auto" data-node-id="2143:118">خروج از سیستم</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2143:119" data-name="logout-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2143:120" data-name="Frame"><div className="absolute inset-[16.67%_11.11%_16.67%_19.44%]" data-node-id="2143:121" data-name="Group"><div className="absolute inset-[-6.67%_-6.4%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup4} /></div></div></div></div></button>
      </div>
    </div>
  );
}
