import { Link } from "react-router-dom";
import "../index.css";

const imgChatGptImage1 = "/assets/emdad/dashboard/logo.png";
const imgEllipse = "/assets/emdad/fund-synergy/summary-eligible.svg";
const imgEllipse1 = "/assets/emdad/fund-synergy/summary-company.svg";
const imgEllipse2 = "/assets/emdad/fund-synergy/summary-allocation.svg";
const imgGroup = "/assets/emdad/dashboard/group.svg";
const imgGroup1 = "/assets/emdad/dashboard/group1.svg";
const imgCertificateIcon = "/assets/emdad/dashboard/certificate-icon.svg";
const imgFundSynergyIcon = "/assets/emdad/dashboard/fund-synergy-icon.svg";
const imgGroup2 = "/assets/emdad/dashboard/group2.svg";
const imgGroup3 = "/assets/emdad/dashboard/group3.svg";
const imgGroup4 = "/assets/emdad/dashboard/group4.svg";

export default function EmdadFundSynergy() {
  return (
    <div className="emdad-panel bg-[#f5f8fb] relative w-full h-full" data-node-id="2222:2" data-name="emdad-fund-synergy">
      <div className="absolute bg-[#f5f8fb] content-stretch flex flex-col gap-[16px] h-[900px] items-start left-0 overflow-clip px-[28px] py-[22px] top-0 w-[1216px]" data-node-id="2222:3" data-name="Main Content">
        <div className="[word-break:break-word] bg-white border border-[#e4ebf1] border-solid h-[72px] leading-[0] overflow-clip relative rounded-[12px] shrink-0 text-right w-full" data-node-id="2222:4" data-name="header">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[32px] justify-center left-[1131px] text-[#17324d] text-[22px] top-[23px] w-[432px]" data-node-id="2222:5"><p className="leading-[normal]" dir="auto">هم‌افزایی صندوق</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[1131px] text-[#60758a] text-[11px] top-[49px] w-[652px]" data-node-id="2222:6"><p className="leading-[normal]" dir="auto">مدیریت سهم ۱۰٪ پرداخت‌های نقدی شرکت‌ها و انتقال آن به صندوق</p></div>
        </div>

        <div className="h-[92px] overflow-clip relative shrink-0 w-full" data-node-id="2222:7" data-name="summary-row">
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[92px] left-0 overflow-clip rounded-[12px] top-0 w-[372px]" data-node-id="2222:8" data-name="summary-card">
            <div className="absolute left-[17px] size-[8px] top-[17px]" data-node-id="2222:9" data-name="Ellipse"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse} /></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[351px] text-[#60758a] text-[12px] text-right top-[19px] w-[304px]" data-node-id="2222:10"><p className="leading-[normal]" dir="auto">پرداخت‌های مشمول</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[351px] text-[#159455] text-[22px] text-right top-[47px] w-[334px]" data-node-id="2222:11"><p className="leading-[normal]">۱</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[16px] justify-center leading-[0] left-[351px] text-[#60758a] text-[10px] text-right top-[72px] w-[334px]" data-node-id="2222:12"><p className="leading-[normal]" dir="auto">پرداخت نقدی با منبع شرکت</p></div>
          </div>
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[92px] left-[394px] overflow-clip rounded-[12px] top-0 w-[372px]" data-node-id="2222:13" data-name="summary-card">
            <div className="absolute left-[17px] size-[8px] top-[17px]" data-node-id="2222:14" data-name="Ellipse"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse1} /></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[351px] text-[#60758a] text-[12px] text-right top-[19px] w-[304px]" data-node-id="2222:15"><p className="leading-[normal]" dir="auto">مبلغ منابع شرکت</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[351px] text-[#2094e3] text-[22px] text-right top-[47px] w-[334px]" data-node-id="2222:16"><p className="leading-[normal]" dir="auto">۲۰۰ میلیون تومان</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[16px] justify-center leading-[0] left-[351px] text-[#60758a] text-[10px] text-right top-[72px] w-[334px]" data-node-id="2222:17"><p className="leading-[normal]" dir="auto">مبلغ نقدی ثبت‌شده</p></div>
          </div>
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[92px] left-[788px] overflow-clip rounded-[12px] top-0 w-[372px]" data-node-id="2222:18" data-name="summary-card">
            <div className="absolute left-[17px] size-[8px] top-[17px]" data-node-id="2222:19" data-name="Ellipse"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse2} /></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[351px] text-[#60758a] text-[12px] text-right top-[19px] w-[304px]" data-node-id="2222:20"><p className="leading-[normal]" dir="auto">سهم قابل تخصیص به صندوق</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[351px] text-[#17324d] text-[22px] text-right top-[47px] w-[334px]" data-node-id="2222:21"><p className="leading-[normal]" dir="auto">۲۰ میلیون تومان</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[16px] justify-center leading-[0] left-[351px] text-[#60758a] text-[10px] text-right top-[72px] w-[334px]" data-node-id="2222:22"><p className="leading-[normal]" dir="auto">۱۰٪ منابع نقدی شرکت</p></div>
          </div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[74px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2222:23" data-name="toolbar">
          <button type="button" className="absolute bg-[#f5f8fb] block border border-[#e4ebf1] border-solid cursor-pointer h-[42px] left-[645px] overflow-clip rounded-[8px] top-[15px] w-[486px]" data-node-id="2222:24" data-name="search"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[24px] justify-center leading-[0] left-[469px] text-[#60758a] text-[11px] text-right top-[20px] w-[454px]" data-node-id="2222:25"><p className="leading-[normal]" dir="auto">جستجو در شرکت یا پروژه</p></div></button>
          <button type="button" className="absolute bg-white block border border-[#e4ebf1] border-solid cursor-pointer h-[42px] left-[413px] overflow-clip rounded-[8px] top-[15px] w-[212px]" data-node-id="2222:26" data-name="status-filter"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[24px] justify-center leading-[0] left-[195px] text-[#17324d] text-[11px] text-right top-[20px] w-[180px]" data-node-id="2222:27"><p className="leading-[normal]" dir="auto">همه وضعیت‌ها</p></div></button>
          <div className="absolute bg-[#ebf6fd] h-[28px] left-[19px] overflow-clip rounded-[14px] top-[22px] w-[112px]" data-node-id="2222:28" data-name="count-pill"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[56px] text-[#2094e3] text-[11px] text-center top-[14px] w-[96px]" data-node-id="2222:29"><p className="leading-[normal]" dir="auto">۱ مورد</p></div></div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[296px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2222:30" data-name="fund-synergy-table">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[1131px] text-[#17324d] text-[18px] text-right top-[29px] w-[372px]" data-node-id="2222:31"><p className="leading-[normal]" dir="auto">پرداخت‌های مشمول هم‌افزایی</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[10px] text-right top-[52px] w-[482px]" data-node-id="2222:32"><p className="leading-[normal]" dir="auto">فقط پرداخت‌های نقدی با منبع شرکت وارد این فهرست می‌شوند</p></div>
          <div className="[word-break:break-word] absolute bg-[#f5f8fb] font-sans font-medium h-[36px] leading-[0] left-[19px] overflow-clip rounded-[8px] text-[#60758a] text-[10px] text-right top-[81px] w-[1120px]" data-node-id="2222:33" data-name="table-header">
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[1104px] top-[18px] w-[74px]" data-node-id="2222:34"><p className="leading-[normal]" dir="auto">ردیف</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[1030px] top-[18px] w-[300px]" data-node-id="2222:35"><p className="leading-[normal]" dir="auto">پروژه / شرکت</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[730px] top-[18px] w-[210px]" data-node-id="2222:36"><p className="leading-[normal]" dir="auto">مبلغ پرداخت نقدی</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[520px] top-[18px] w-[160px]" data-node-id="2222:37"><p className="leading-[normal]" dir="auto">سهم ۱۰٪ صندوق</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[360px] top-[18px] w-[155px]" data-node-id="2222:38"><p className="leading-[normal]" dir="auto">وضعیت</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[205px] top-[18px] w-[185px]" data-node-id="2222:39"><p className="leading-[normal]" dir="auto">اقدام</p></div>
          </div>
          <div className="absolute bg-[#f5f8fb] border border-[#e4ebf1] border-solid h-[64px] left-[19px] overflow-clip rounded-[8px] top-[129px] w-[1120px]" data-node-id="2222:40" data-name="fund-synergy-row">
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[44px] justify-center leading-[0] left-[1103px] text-[#17324d] text-[12px] text-right top-[31px] w-[74px]" data-node-id="2222:41"><p className="leading-[normal]">۱</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[22px] justify-center leading-[0] left-[1029px] text-[#17324d] text-[12px] text-right top-[18px] w-[300px]" data-node-id="2222:42"><p className="leading-[normal]" dir="auto">سلامت خانواده</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[1029px] text-[#60758a] text-[10px] text-right top-[40px] w-[300px]" data-node-id="2222:43"><p className="leading-[normal]" dir="auto">پایدار پرداز خلاق آریا · منبع: شرکت</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[40px] justify-center leading-[0] left-[729px] text-[#17324d] text-[11px] text-right top-[29px] w-[210px]" data-node-id="2222:44"><p className="leading-[normal]" dir="auto">۲۰۰ میلیون تومان</p></div>
            <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[40px] justify-center leading-[0] left-[519px] text-[#17324d] text-[12px] text-right top-[29px] w-[160px]" data-node-id="2222:45"><p className="leading-[normal]" dir="auto">۲۰ میلیون تومان</p></div>
            <div className="absolute bg-[#e8f7ef] h-[28px] left-[214px] overflow-clip rounded-[14px] top-[17px] w-[135px]" data-node-id="2222:46" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[66px] text-[#159455] text-[11px] text-center top-[14px] w-[116px]" data-node-id="2222:47"><p className="leading-[normal]" dir="auto">در انتظار تخصیص</p></div></div>
            <Link to="/panel/emdad/fund-synergy/allocation" className="absolute bg-[#2094e3] block border border-[#2094e3] border-solid cursor-pointer h-[38px] left-[27px] overflow-clip rounded-[8px] top-[12px] w-[160px]" data-node-id="2222:48" data-name="detail-button"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[74px] text-[12px] text-center text-white top-[18px] w-[130px]" data-node-id="2222:49"><p className="leading-[normal]" dir="auto">ثبت تخصیص</p></div></Link>
          </div>
          <div className="absolute bg-[#ebf6fd] h-[28px] left-[19px] overflow-clip rounded-[8px] top-[253px] w-[1120px]" data-node-id="2222:50" data-name="table-note"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[1104px] text-[#60758a] text-[10px] text-right top-[14px] w-[1088px]" data-node-id="2222:51"><p className="leading-[normal]" dir="auto">پرداخت‌هایی که منبع آن‌ها صندوق است در این بخش نمایش داده نمی‌شوند و مشمول تخصیص ۱۰٪ نیستند.</p></div></div>
          <div className="absolute bg-[#f5f8fb] content-stretch flex h-[40px] items-center justify-between left-[19px] overflow-clip px-[10px] rounded-[8px] top-[205px] w-[1120px]" data-node-id="2222:52" data-name="pagination-footer">
            <div className="content-stretch flex gap-[8px] h-[30px] items-center overflow-clip relative shrink-0" data-node-id="2222:53" data-name="pagination-controls">
              <button type="button" className="bg-white border border-[#e4ebf1] border-solid content-stretch cursor-pointer flex h-[30px] items-center justify-center opacity-50 overflow-clip relative rounded-[7px] shrink-0 w-[52px]" data-node-id="2222:54" data-name="pagination-بعدی"><div className="[word-break:break-word] flex flex-col font-sans font-medium h-[22px] justify-center leading-[0] relative shrink-0 text-[#17324d] text-[10px] text-center w-[40px]" data-node-id="2222:55"><p className="leading-[normal]" dir="auto">بعدی</p></div></button>
              <div className="bg-[#2094e3] content-stretch flex items-center justify-center overflow-clip relative rounded-[7px] shrink-0 size-[30px]" data-node-id="2222:56" data-name="pagination-active-page"><div className="[word-break:break-word] flex flex-col font-sans font-medium h-[22px] justify-center leading-[0] relative shrink-0 text-[10px] text-center text-white w-[24px]" data-node-id="2222:57"><p className="leading-[normal]">۱</p></div></div>
              <button type="button" className="bg-white border border-[#e4ebf1] border-solid content-stretch cursor-pointer flex h-[30px] items-center justify-center opacity-50 overflow-clip relative rounded-[7px] shrink-0 w-[52px]" data-node-id="2222:58" data-name="pagination-قبلی"><div className="[word-break:break-word] flex flex-col font-sans font-medium h-[22px] justify-center leading-[0] relative shrink-0 text-[#17324d] text-[10px] text-center w-[40px]" data-node-id="2222:59"><p className="leading-[normal]" dir="auto">قبلی</p></div></button>
            </div>
            <div className="[word-break:break-word] flex flex-col font-sans font-normal h-[22px] justify-center leading-[0] relative shrink-0 text-[#60758a] text-[10px] text-right w-[240px]" data-node-id="2222:60"><p className="leading-[normal]" dir="auto">نمایش ۱ تا ۱ از ۱</p></div>
          </div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[104px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2222:61" data-name="fund-synergy-rule">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[1131px] text-[#17324d] text-[16px] text-right top-[27px] w-[332px]" data-node-id="2222:62"><p className="leading-[normal]" dir="auto">قاعده هم‌افزایی صندوق</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[38px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[11px] text-right top-[62px] w-[972px]" data-node-id="2222:63"><p className="leading-[normal]" dir="auto">فقط پرداخت‌های نقدی با منبع شرکت مشمول تخصیص ۱۰٪ هستند. تأمین مالی انجام‌شده از منابع خود صندوق دوباره مشمول ۱۰٪ نمی‌شود.</p></div>
          <div className="absolute bg-[#e8f7ef] h-[28px] left-[19px] overflow-clip rounded-[14px] top-[61px] w-[116px]" data-node-id="2222:64" data-name="status-pill"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[58px] text-[#159455] text-[11px] text-center top-[14px] w-[100px]" data-node-id="2222:65"><p className="leading-[normal]" dir="auto">منبع: شرکت</p></div></div>
        </div>

        <Link to="/panel/emdad/fund-synergy/history" className="bg-white block border border-[#e4ebf1] border-solid cursor-pointer h-[92px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2222:66" data-name="fund-synergy-actions">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[1131px] text-[#17324d] text-[14px] text-right top-[23px] w-[282px]" data-node-id="2222:67"><p className="leading-[normal]" dir="auto">ثبت تخصیص به صندوق</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[22px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[10px] text-right top-[48px] w-[682px]" data-node-id="2222:68"><p className="leading-[normal]" dir="auto">پس از واریز سهم ۱۰٪، رسید تراکنش در سوابق مالی ثبت و قابل پیگیری می‌شود.</p></div>
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[38px] left-[19px] overflow-clip rounded-[8px] top-[45px] w-[190px]" data-node-id="2222:69" data-name="financial-reports-button"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[94px] text-[#17324d] text-[12px] text-center top-[18px] w-[170px]" data-node-id="2222:70"><p className="leading-[normal]" dir="auto">مشاهده همه سوابق</p></div></div>
        </Link>
      </div>

      <div className="absolute bg-[#17324d] content-stretch flex flex-col gap-[10px] h-[900px] items-end left-[1216px] pb-[18px] pt-[20px] px-[16px] top-0 w-[224px]" data-node-id="2222:71" data-name="colored-sidebar">
        <div className="bg-white content-stretch flex h-[56px] items-center justify-end overflow-clip px-[10px] py-[8px] relative rounded-[12px] shrink-0 w-[192px]" data-node-id="2222:72" data-name="brand-logo"><div className="h-[40px] relative shrink-0 w-[118px]" data-node-id="2222:73" data-name="ChatGPT Image ۲۹ مرداد ۱۴۰۵، ۱۵_۱۶_۳۵ 1"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="" className="absolute h-full left-[5.28%] max-w-none top-0 w-[100.73%]" src={imgChatGptImage1} /></div></div></div>
        <div className="[word-break:break-word] content-stretch flex flex-col gap-[3px] h-[64px] items-start justify-end overflow-clip px-[8px] py-[7px] relative shrink-0 text-center w-[192px]" data-node-id="2222:74" data-name="panel-identity"><p className="font-sans font-medium h-[24px] leading-[normal] relative shrink-0 text-[13px] text-white w-[176px]" dir="auto" data-node-id="2222:75">سامانه ماه</p><div className="flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] relative shrink-0 text-[#d8e7f3] text-[10px] w-[176px]" data-node-id="2222:76"><p className="leading-[normal]" dir="auto">پنل کمیته امداد</p></div></div>
        <Link to="/panel/emdad" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2222:77" data-name="dashboard-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2222:78">داشبورد</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2222:79" data-name="dashboard-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2222:80" data-name="Frame"><div className="absolute inset-[11.11%]" data-node-id="2222:81" data-name="Group"><div className="absolute inset-[-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup} /></div></div></div></div></Link>
        <Link to="/panel/emdad/release-requests" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2222:86" data-name="release-requests-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2222:87">درخواست‌های آزادسازی</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2222:88" data-name="users-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2222:89" data-name="Frame"><div className="absolute inset-[22.22%_13.89%_19.44%_13.89%]" data-node-id="2222:90" data-name="Group"><div className="absolute inset-[-7.62%_-6.15%]"><img alt="" className="block max-w-none size-full" src={imgGroup1} /></div></div></div></div></Link>
        <Link to="/panel/emdad/article172-approvals" className="block cursor-pointer h-[38px] overflow-clip relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2222:93" data-name="article-172-approvals-nav"><p className="-translate-x-full [word-break:break-word] absolute font-sans font-normal leading-[normal] left-[152px] text-[12px] text-right text-white top-[9.5px] w-[142px]" dir="auto" data-node-id="2222:94">تأیید گواهی ماده ۱۷۲</p><div className="absolute left-[162px] size-[18px] top-[10px]" data-node-id="2222:95" data-name="certificate-icon"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgCertificateIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy" className="bg-[#2094e3] content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2223:83" data-name="fund-synergy-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2223:84">هم‌افزایی صندوق</p><div className="relative shrink-0 size-[18px]" data-node-id="2226:44" data-name="fund-synergy-icon"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgFundSynergyIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy/history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2237:235" data-name="fund-synergy-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2237:236">سوابق هم‌افزایی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2237:237" data-name="project-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2237:238" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2237:239" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/payment-history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2222:99" data-name="payment-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2222:100">سوابق پرداخت</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2222:101" data-name="project-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2222:102" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2222:103" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/financial-reports" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2222:107" data-name="financial-reports-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2222:108">گزارش‌های مالی</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2222:109" data-name="milestone-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2222:110" data-name="Frame"><div className="absolute inset-[13.89%_11.11%]" data-node-id="2222:111" data-name="Group"><div className="absolute inset-[-6.15%_-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup3} /></div></div></div></div></Link>
        <Link to="/panel/emdad/fund-returns" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2382:470" data-name="fund-returns-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2382:471">منابع برگشتی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2382:472" data-name="project-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2382:473" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2382:474" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <div className="flex-[1_0_0] min-h-px relative w-[192px]" data-node-id="2222:116" data-name="sidebar-spacer" />
        <button type="button" className="bg-white content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end opacity-96 overflow-clip px-[12px] relative rounded-[9px] shrink-0 w-[192px]" data-node-id="2222:117" data-name="logout-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[#17324d] text-[12px] text-right w-[142px]" dir="auto" data-node-id="2222:118">خروج از سیستم</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2222:119" data-name="logout-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0" data-node-id="2222:120" data-name="Frame"><div className="absolute inset-[16.67%_11.11%_16.67%_19.44%]" data-node-id="2222:121" data-name="Group"><div className="absolute inset-[-6.67%_-6.4%]"><img alt="" className="block max-w-none size-full" src={imgGroup4} /></div></div></div></div></button>
      </div>
    </div>
  );
}
