import { Link } from "react-router-dom";
import "../../index.css";

const imgChatGptImage1 = "/assets/emdad/dashboard/logo.png";
const imgNumber = "/assets/emdad/article172-approvals/detail/number-active.svg";
const imgNumber1 = "/assets/emdad/article172-approvals/detail/number-pending.svg";
const imgGroup = "/assets/emdad/dashboard/group.svg";
const imgGroup1 = "/assets/emdad/dashboard/group1.svg";
const imgCertificateIcon = "/assets/emdad/dashboard/certificate-icon.svg";
const imgFundSynergyIcon = "/assets/emdad/dashboard/fund-synergy-icon.svg";
const imgGroup2 = "/assets/emdad/dashboard/group2.svg";
const imgGroup3 = "/assets/emdad/dashboard/group3.svg";
const imgGroup4 = "/assets/emdad/dashboard/group4.svg";

export default function EmdadArticle172RequestDetail() {
  return (
    <div className="emdad-panel bg-[#f5f8fb] relative w-full h-full" data-node-id="2163:2" data-name="emdad-article172-request-detail">
      <div className="absolute bg-[#f5f8fb] h-[900px] left-0 overflow-clip top-0 w-[1216px]" data-node-id="2163:3" data-name="Main Content">
        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[64px] left-[28px] overflow-clip rounded-[12px] top-[22px] w-[1160px]" data-node-id="2163:132" data-name="header">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[30px] justify-center leading-[0] left-[1139px] text-[#17324d] text-[20px] text-right top-[20px] w-[660px]" data-node-id="2163:133"><p className="leading-[normal]" dir="auto">بررسی درخواست گواهی ماده ۱۷۲</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[1139px] text-[#60758a] text-[10px] text-right top-[43px] w-[750px]" data-node-id="2163:134"><p className="leading-[normal]" dir="auto">بررسی نهایی پرونده پس از ثبت پرداخت واجد شرایط و تکمیل الزامات قانونی</p></div>
          <div className="absolute bg-[#edf7fe] h-[28px] left-[19px] overflow-clip rounded-[14px] top-[17px] w-[130px]" data-node-id="2163:135" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[65px] text-[#2094e3] text-[11px] text-center top-[14px] w-[114px]" data-node-id="2163:136"><p className="leading-[normal]" dir="auto">آماده بررسی</p></div></div>
        </div>

        <div className="[word-break:break-word] absolute bg-white border border-[#e4ebf1] border-solid h-[190px] leading-[0] left-[28px] overflow-clip rounded-[12px] text-right top-[104px] w-[1160px]" data-node-id="2163:137" data-name="request-summary">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[1139px] text-[#17324d] text-[16px] top-[27px] w-[320px]" data-node-id="2163:138"><p className="leading-[normal]" dir="auto">خلاصه پرونده</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[1139px] text-[#60758a] text-[10px] top-[48px] w-[580px]" data-node-id="2163:139"><p className="leading-[normal]" dir="auto">اطلاعات ثبت‌شده در پنل شرکت و وضعیت پرداخت مرتبط با درخواست</p></div>
          <div className="absolute bg-[#f8fafc] h-[48px] left-[774px] overflow-clip rounded-[8px] top-[69px] w-[350px]" data-node-id="2163:140" data-name="field"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[17px] justify-center left-[338px] text-[#60758a] text-[10px] top-[12.5px] w-[326px]" data-node-id="2163:141"><p className="leading-[normal]" dir="auto">شرکت</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[23px] justify-center left-[338px] text-[#17324d] text-[12px] top-[32.5px] w-[326px]" data-node-id="2163:142"><p className="leading-[normal]" dir="auto">پایدار پرداز خلاق آریا</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[48px] left-[404px] overflow-clip rounded-[8px] top-[69px] w-[350px]" data-node-id="2163:143" data-name="field"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[17px] justify-center left-[338px] text-[#60758a] text-[10px] top-[12.5px] w-[326px]" data-node-id="2163:144"><p className="leading-[normal]" dir="auto">شناسه ملی</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[23px] justify-center left-[338px] text-[#17324d] text-[12px] top-[32.5px] w-[326px]" data-node-id="2163:145"><p className="leading-[normal]">۱۰۱۰۴۵۸۶۹۲۱</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[48px] left-[34px] overflow-clip rounded-[8px] top-[69px] w-[350px]" data-node-id="2163:146" data-name="field"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[17px] justify-center left-[338px] text-[#60758a] text-[10px] top-[12.5px] w-[326px]" data-node-id="2163:147"><p className="leading-[normal]" dir="auto">پروژه</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[23px] justify-center left-[338px] text-[#17324d] text-[12px] top-[32.5px] w-[326px]" data-node-id="2163:148"><p className="leading-[normal]" dir="auto">سلامت خانواده</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[48px] left-[774px] overflow-clip rounded-[8px] top-[127px] w-[350px]" data-node-id="2163:149" data-name="field"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[17px] justify-center left-[338px] text-[#60758a] text-[10px] top-[12.5px] w-[326px]" data-node-id="2163:150"><p className="leading-[normal]" dir="auto">وضعیت پرونده مالیاتی</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[23px] justify-center left-[338px] text-[#159455] text-[12px] top-[32.5px] w-[326px]" data-node-id="2163:151"><p className="leading-[normal]" dir="auto">فعال</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[48px] left-[404px] overflow-clip rounded-[8px] top-[127px] w-[350px]" data-node-id="2163:152" data-name="field"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[17px] justify-center left-[338px] text-[#60758a] text-[10px] top-[12.5px] w-[326px]" data-node-id="2163:153"><p className="leading-[normal]" dir="auto">وضعیت پرداخت</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[23px] justify-center left-[338px] text-[#159455] text-[12px] top-[32.5px] w-[326px]" data-node-id="2163:154"><p className="leading-[normal]" dir="auto">پرداخت موفق</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[48px] left-[34px] overflow-clip rounded-[8px] top-[127px] w-[350px]" data-node-id="2163:155" data-name="field"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[17px] justify-center left-[338px] text-[#60758a] text-[10px] top-[12.5px] w-[326px]" data-node-id="2163:156"><p className="leading-[normal]" dir="auto">مسیر پرداخت</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[23px] justify-center left-[338px] text-[#17324d] text-[12px] top-[32.5px] w-[326px]" data-node-id="2163:157"><p className="leading-[normal]" dir="auto">حساب کمیته امداد</p></div></div>
        </div>

        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[310px] left-[620px] overflow-clip rounded-[12px] top-[314px] w-[568px]" data-node-id="2163:158" data-name="final-controls">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[551px] text-[#17324d] text-[16px] text-right top-[27px] w-[272px]" data-node-id="2163:159"><p className="leading-[normal]" dir="auto">کنترل‌های نهایی</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[551px] text-[#60758a] text-[10px] text-right top-[48px] w-[452px]" data-node-id="2163:160"><p className="leading-[normal]" dir="auto">مواردی که مبنای تصمیم نهایی کمیته امداد هستند</p></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[69px] w-[536px]" data-node-id="2163:161" data-name="check-row"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[516px] text-[#17324d] text-[12px] text-right top-[15px] w-[246px]" data-node-id="2163:162"><p className="leading-[normal]" dir="auto">اطلاعات حقوقی شرکت</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[516px] text-[#60758a] text-[10px] text-right top-[34px] w-[352px]" data-node-id="2163:163"><p className="leading-[normal]" dir="auto">شناسه ملی شرکت ثبت شده است</p></div><div className="absolute bg-[#eaf8f1] h-[28px] left-[12px] overflow-clip rounded-[14px] top-[12px] w-[136px]" data-node-id="2163:164" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[68px] text-[#159455] text-[11px] text-center top-[14px] w-[120px]" data-node-id="2163:165"><p className="leading-[normal]" dir="auto">ثبت‌شده</p></div></div></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[127px] w-[536px]" data-node-id="2163:166" data-name="check-row"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[516px] text-[#17324d] text-[12px] text-right top-[15px] w-[246px]" data-node-id="2163:167"><p className="leading-[normal]" dir="auto">پرونده مالیاتی</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[516px] text-[#60758a] text-[10px] text-right top-[34px] w-[352px]" data-node-id="2163:168"><p className="leading-[normal]" dir="auto">وضعیت ثبت‌شده شرکت فعال است</p></div><div className="absolute bg-[#eaf8f1] h-[28px] left-[12px] overflow-clip rounded-[14px] top-[12px] w-[136px]" data-node-id="2163:169" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[68px] text-[#159455] text-[11px] text-center top-[14px] w-[120px]" data-node-id="2163:170"><p className="leading-[normal]" dir="auto">فعال</p></div></div></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[185px] w-[536px]" data-node-id="2163:171" data-name="check-row"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[516px] text-[#17324d] text-[12px] text-right top-[15px] w-[246px]" data-node-id="2163:172"><p className="leading-[normal]" dir="auto">پرداخت واجد شرایط</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[516px] text-[#60758a] text-[10px] text-right top-[34px] w-[352px]" data-node-id="2163:173"><p className="leading-[normal]" dir="auto">پرداخت مستقیم برای درخواست ثبت شده است</p></div><div className="absolute bg-[#eaf8f1] h-[28px] left-[12px] overflow-clip rounded-[14px] top-[12px] w-[136px]" data-node-id="2163:174" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[68px] text-[#159455] text-[11px] text-center top-[14px] w-[120px]" data-node-id="2163:175"><p className="leading-[normal]" dir="auto">ثبت‌شده</p></div></div></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[243px] w-[536px]" data-node-id="2163:176" data-name="check-row"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[516px] text-[#17324d] text-[12px] text-right top-[15px] w-[246px]" data-node-id="2163:177"><p className="leading-[normal]" dir="auto">بررسی ضوابط قانونی</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[516px] text-[#60758a] text-[10px] text-right top-[34px] w-[352px]" data-node-id="2163:178"><p className="leading-[normal]" dir="auto">تأیید نهایی توسط کمیته امداد انجام می‌شود</p></div><div className="absolute bg-[#edf7fe] h-[28px] left-[12px] overflow-clip rounded-[14px] top-[12px] w-[136px]" data-node-id="2163:179" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[68px] text-[#2094e3] text-[11px] text-center top-[14px] w-[120px]" data-node-id="2163:180"><p className="leading-[normal]" dir="auto">نیازمند تصمیم</p></div></div></div>
        </div>

        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[310px] left-[28px] overflow-clip rounded-[12px] top-[314px] w-[568px]" data-node-id="2163:181" data-name="issuance-process">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[551px] text-[#17324d] text-[16px] text-right top-[27px] w-[272px]" data-node-id="2163:182"><p className="leading-[normal]" dir="auto">مسیر صدور گواهی</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[551px] text-[#60758a] text-[10px] text-right top-[48px] w-[452px]" data-node-id="2163:183"><p className="leading-[normal]" dir="auto">وضعیت پرونده در مسیر صدور ماده ۱۷۲</p></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[69px] w-[536px]" data-node-id="2163:184" data-name="process-step"><div className="absolute left-[484px] size-[32px] top-[10px]" data-node-id="2163:185" data-name="number"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgNumber} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[500px] size-[32px] text-[12px] text-center text-white top-[26px]" data-node-id="2163:186"><p className="leading-[normal]">۱</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[472px] text-[#17324d] text-[12px] text-right top-[15px] w-[224px]" data-node-id="2163:187"><p className="leading-[normal]" dir="auto">ثبت پرداخت</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[472px] text-[#60758a] text-[10px] text-right top-[34px] w-[356px]" data-node-id="2163:188"><p className="leading-[normal]" dir="auto">پرداخت مستقیم ثبت شده است</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[127px] w-[536px]" data-node-id="2163:189" data-name="process-step"><div className="absolute left-[484px] size-[32px] top-[10px]" data-node-id="2163:190" data-name="number"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgNumber} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[500px] size-[32px] text-[12px] text-center text-white top-[26px]" data-node-id="2163:191"><p className="leading-[normal]">۲</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[472px] text-[#17324d] text-[12px] text-right top-[15px] w-[224px]" data-node-id="2163:192"><p className="leading-[normal]" dir="auto">تطبیق اطلاعات</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[472px] text-[#60758a] text-[10px] text-right top-[34px] w-[356px]" data-node-id="2163:193"><p className="leading-[normal]" dir="auto">اطلاعات حقوقی و مالیاتی ثبت شده است</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[185px] w-[536px]" data-node-id="2163:194" data-name="process-step"><div className="absolute left-[484px] size-[32px] top-[10px]" data-node-id="2163:195" data-name="number"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgNumber} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[500px] size-[32px] text-[12px] text-center text-white top-[26px]" data-node-id="2163:196"><p className="leading-[normal]">۳</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[472px] text-[#17324d] text-[12px] text-right top-[15px] w-[224px]" data-node-id="2163:197"><p className="leading-[normal]" dir="auto">بررسی قانونی</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[472px] text-[#60758a] text-[10px] text-right top-[34px] w-[356px]" data-node-id="2163:198"><p className="leading-[normal]" dir="auto">پرونده آماده تصمیم نهایی کمیته امداد است</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[52px] left-[15px] overflow-clip rounded-[8px] top-[243px] w-[536px]" data-node-id="2163:199" data-name="process-step"><div className="absolute left-[484px] size-[32px] top-[10px]" data-node-id="2163:200" data-name="number"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgNumber1} /></div><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[500px] size-[32px] text-[#60758a] text-[12px] text-center top-[26px]" data-node-id="2163:201"><p className="leading-[normal]">۴</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[20px] justify-center leading-[0] left-[472px] text-[#17324d] text-[12px] text-right top-[15px] w-[224px]" data-node-id="2163:202"><p className="leading-[normal]" dir="auto">صدور گواهی</p></div><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[472px] text-[#60758a] text-[10px] text-right top-[34px] w-[356px]" data-node-id="2163:203"><p className="leading-[normal]" dir="auto">پس از تأیید نهایی قابل صدور و دریافت است</p></div></div>
        </div>

        <div className="[word-break:break-word] absolute bg-[#edf7fe] border border-[#cfe8f8] border-solid h-[84px] leading-[0] left-[28px] overflow-clip rounded-[12px] text-right top-[644px] w-[1160px]" data-node-id="2163:204" data-name="role-note"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[1139px] text-[#17324d] text-[14px] top-[23px] w-[320px]" data-node-id="2163:205"><p className="leading-[normal]" dir="auto">دامنه مسئولیت کمیته امداد</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[1139px] text-[#60758a] text-[11px] top-[49px] w-[940px]" data-node-id="2163:206"><p className="leading-[normal]" dir="auto">این صفحه برای تأیید نهایی شرایط گواهی ماده ۱۷۲ است؛ کمیته امداد در این مرحله ارزیابی محتوایی پروژه را انجام نمی‌دهد.</p></div></div>

        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[124px] left-[28px] overflow-clip rounded-[12px] top-[748px] w-[1160px]" data-node-id="2163:207" data-name="final-decision">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[26px] justify-center leading-[0] left-[1139px] text-[#17324d] text-[15px] text-right top-[28px] w-[300px]" data-node-id="2163:208"><p className="leading-[normal]" dir="auto">تصمیم نهایی</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[22px] justify-center leading-[0] left-[1139px] text-[#60758a] text-[11px] text-right top-[54px] w-[670px]" data-node-id="2163:209"><p className="leading-[normal]" dir="auto">با تأیید نهایی، پرونده وارد مرحله صدور گواهی می‌شود و شماره و تاریخ صدور پس از صدور ثبت خواهند شد.</p></div>
          <Link to="/panel/emdad/article172-approvals/success" className="absolute bg-[#2094e3] block cursor-pointer h-[40px] left-[19px] overflow-clip rounded-[8px] top-[67px] w-[220px]" data-node-id="2163:210" data-name="approve-final"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[40px] justify-center leading-[0] left-[110px] text-[12px] text-center text-white top-[20px] w-[200px]" data-node-id="2163:211"><p className="leading-[normal]" dir="auto">تأیید نهایی درخواست</p></div></Link>
          <Link to="/panel/emdad/article172-approvals" className="absolute bg-white block border border-[#e4ebf1] border-solid cursor-pointer h-[40px] left-[251px] overflow-clip rounded-[8px] top-[67px] w-[190px]" data-node-id="2163:212" data-name="back-to-list"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[40px] justify-center leading-[0] left-[94px] text-[#17324d] text-[12px] text-center top-[19px] w-[170px]" data-node-id="2163:213"><p className="leading-[normal]" dir="auto">بازگشت به درخواست‌ها</p></div></Link>
        </div>
      </div>

      <div className="absolute bg-[#17324d] content-stretch flex flex-col gap-[10px] h-[900px] items-end left-[1216px] pb-[18px] pt-[20px] px-[16px] top-0 w-[224px]" data-node-id="2163:70" data-name="colored-sidebar">
        <div className="bg-white content-stretch flex h-[56px] items-center justify-end overflow-clip px-[10px] py-[8px] relative rounded-[12px] shrink-0 w-[192px]" data-node-id="2163:71" data-name="brand-logo"><div className="h-[40px] relative shrink-0 w-[118px]" data-node-id="2163:72" data-name="ChatGPT Image ۲۹ مرداد ۱۴۰۵، ۱۵_۱۶_۳۵ 1"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="" className="absolute h-full left-[5.28%] max-w-none top-0 w-[100.73%]" src={imgChatGptImage1} /></div></div></div>
        <div className="[word-break:break-word] content-stretch flex flex-col gap-[3px] h-[64px] items-start justify-end overflow-clip px-[8px] py-[7px] relative shrink-0 text-center w-[192px]" data-node-id="2163:73" data-name="panel-identity"><p className="font-sans font-medium h-[24px] leading-[normal] relative shrink-0 text-[13px] text-white w-[176px]" dir="auto" data-node-id="2163:74">سامانه ماه</p><div className="flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] relative shrink-0 text-[#d8e7f3] text-[10px] w-[176px]" data-node-id="2163:75"><p className="leading-[normal]" dir="auto">پنل کمیته امداد</p></div></div>
        <Link to="/panel/emdad" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2163:76" data-name="dashboard-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2163:77">داشبورد</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2163:78" data-name="dashboard-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[11.11%]"><div className="absolute inset-[-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup} /></div></div></div></div></Link>
        <Link to="/panel/emdad/release-requests" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2163:85" data-name="release-requests-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2163:86">درخواست‌های آزادسازی</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2163:87" data-name="users-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[22.22%_13.89%_19.44%_13.89%]"><div className="absolute inset-[-7.62%_-6.15%]"><img alt="" className="block max-w-none size-full" src={imgGroup1} /></div></div></div></div></Link>
        <Link to="/panel/emdad/article172-approvals" className="bg-[#2094e3] h-[38px] overflow-clip relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2163:92" data-name="article-172-approvals-nav"><p className="-translate-x-full [word-break:break-word] absolute font-sans font-normal leading-[normal] left-[152px] text-[12px] text-right text-white top-[9.5px] w-[142px]" dir="auto" data-node-id="2163:93">تأیید گواهی ماده ۱۷۲</p><div className="absolute left-[162px] size-[18px] top-[10px]" data-node-id="2163:94" data-name="certificate-icon"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgCertificateIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2223:47" data-name="fund-synergy-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2223:48">هم‌افزایی صندوق</p><div className="relative shrink-0 size-[18px]" data-node-id="2226:28" data-name="fund-synergy-icon"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgFundSynergyIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy/history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2237:203" data-name="fund-synergy-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2237:204">سوابق هم‌افزایی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2237:205" data-name="project-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/payment-history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2163:98" data-name="payment-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2163:99">سوابق پرداخت</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2163:100" data-name="project-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/financial-reports" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2163:106" data-name="financial-reports-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2163:107">گزارش‌های مالی</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2163:108" data-name="milestone-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[13.89%_11.11%]"><div className="absolute inset-[-6.15%_-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup3} /></div></div></div></div></Link>
        <Link to="/panel/emdad/fund-returns" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2382:438" data-name="fund-returns-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2382:439">منابع برگشتی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2382:440" data-name="project-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <div className="flex-[1_0_0] min-h-px relative w-[192px]" data-node-id="2163:123" data-name="sidebar-spacer" />
        <button type="button" className="bg-white content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end opacity-96 overflow-clip px-[12px] relative rounded-[9px] shrink-0 w-[192px]" data-node-id="2163:124" data-name="logout-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[#17324d] text-[12px] text-right w-[142px]" dir="auto" data-node-id="2163:125">خروج از سیستم</p><div className="overflow-clip relative shrink-0 size-[18px]" data-node-id="2163:126" data-name="logout-icon"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[16.67%_11.11%_16.67%_19.44%]"><div className="absolute inset-[-6.67%_-6.4%]"><img alt="" className="block max-w-none size-full" src={imgGroup4} /></div></div></div></div></button>
      </div>
    </div>
  );
}
