services:
  - type: web
    name: moon-platform-api
    runtime: docker
    plan: free
    region: frankfurt
    repo: https://github.com/mahdimarzooghi4-debug/moon-platform
    branch: deploy/render-backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moon-platform-postgres
          property: connectionString
      - key: Database__MigrateOnStartup
        value: "true"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Cors__AllowedOrigins__0
        value: https://mahcsr.ir
      - key: Authentication__RequireHttpsMetadata
        value: "true"
      - key: Messaging__OutboxDispatchEnabled
        value: "false"
