import { Link } from "react-router-dom";
import "../../index.css";

const imgChatGptImage1 = "/assets/emdad/dashboard/logo.png";
const imgGroup = "/assets/emdad/dashboard/group.svg";
const imgGroup1 = "/assets/emdad/dashboard/group1.svg";
const imgCertificateIcon = "/assets/emdad/dashboard/certificate-icon.svg";
const imgFundSynergyIcon = "/assets/emdad/dashboard/fund-synergy-icon.svg";
const imgGroup2 = "/assets/emdad/dashboard/group2.svg";
const imgGroup3 = "/assets/emdad/dashboard/group3.svg";
const imgGroup4 = "/assets/emdad/dashboard/group4.svg";

export default function EmdadReleaseRequestDetail() {
  return (
    <div className="emdad-panel bg-[#f5f8fb] relative w-full h-full" data-node-id="2139:2" data-name="emdad-release-request-detail">
      <div className="absolute bg-[#f5f8fb] h-[900px] left-0 overflow-clip top-0 w-[1216px]" data-node-id="2139:3" data-name="Main Content">
        <div className="[word-break:break-word] absolute bg-white h-[64px] leading-[0] left-[28px] overflow-clip rounded-[12px] text-right top-[22px] w-[1160px]" data-node-id="2139:109" data-name="header">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[30px] justify-center left-[1136px] text-[#17324d] text-[22px] top-[20px] w-[1112px]" data-node-id="2139:110"><p className="leading-[normal]" dir="auto">بررسی درخواست آزادسازی وجه</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[1136px] text-[#60758a] text-[11px] top-[46px] w-[1112px]" data-node-id="2139:111"><p className="leading-[normal]" dir="auto">بررسی درخواست مرحله تأییدشده و ثبت تصمیم آزادسازی توسط کمیته امداد</p></div>
        </div>
        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[150px] left-[28px] overflow-clip rounded-[12px] top-[104px] w-[1160px]" data-node-id="2139:112" data-name="request-summary">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[30px] justify-center leading-[0] left-[1131px] text-[#17324d] text-[18px] text-right top-[34px] w-[486px]" data-node-id="2139:113"><p className="leading-[normal]" dir="auto">اشتغال زنان روستایی</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[11px] text-right top-[61px] w-[486px]" data-node-id="2139:114"><p className="leading-[normal]" dir="auto">کسب‌وکار و اشتغال · گلستان</p></div>
          <div className="absolute bg-[#fff7e6] h-[30px] left-[941px] overflow-clip rounded-[15px] top-[91px] w-[190px]" data-node-id="2139:115" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[95px] text-[#c27a10] text-[11px] text-center top-[15px] w-[174px]" data-node-id="2139:116"><p className="leading-[normal]" dir="auto">در انتظار آزادسازی</p></div></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[617px] text-[#60758a] text-[10px] text-right top-[31px] w-[140px]" data-node-id="2139:117"><p className="leading-[normal]" dir="auto">مرحله پروژه</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[617px] text-[#17324d] text-[13px] text-right top-[57px] w-[140px]" data-node-id="2139:118"><p className="leading-[normal]" dir="auto">شناسایی و ارزیابی</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[441px] text-[#60758a] text-[10px] text-right top-[31px] w-[140px]" data-node-id="2139:119"><p className="leading-[normal]" dir="auto">سهم مرحله</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[441px] text-[#17324d] text-[16px] text-right top-[57px] w-[140px]" data-node-id="2139:120"><p className="leading-[normal]">۲۰٪</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[265px] text-[#60758a] text-[10px] text-right top-[31px] w-[140px]" data-node-id="2139:121"><p className="leading-[normal]" dir="auto">ارزیابی مرحله</p></div>
          <div className="absolute bg-[#e9f8f1] h-[30px] left-[91px] overflow-clip rounded-[15px] top-[45px] w-[174px]" data-node-id="2139:122" data-name="evaluation-status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[87px] text-[#159455] text-[11px] text-center top-[15px] w-[158px]" data-node-id="2139:123"><p className="leading-[normal]" dir="auto">تأیید شده توسط آینه</p></div></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[24px] justify-center leading-[0] left-[617px] text-[#60758a] text-[10px] text-right top-[119px] w-[590px]" data-node-id="2139:124"><p className="leading-[normal]" dir="auto">این درخواست پس از تأیید مرحله توسط خانه خلاق و نوآوری آینه وارد صف کمیته امداد شده است.</p></div>
        </div>
        <div className="[word-break:break-word] absolute bg-white border border-[#e4ebf1] border-solid h-[352px] leading-[0] left-[468px] overflow-clip rounded-[12px] top-[274px] w-[720px]" data-node-id="2139:125" data-name="evaluation-and-kpi">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[699px] text-[#17324d] text-[17px] text-right top-[29px] w-[680px]" data-node-id="2139:126"><p className="leading-[normal]" dir="auto">تأیید مرحله و شاخص‌های ثبت‌شده</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[699px] text-[#60758a] text-[10px] text-right top-[54px] w-[680px]" data-node-id="2139:127"><p className="leading-[normal]" dir="auto">اطلاعات ارزیابی آینه برای تصمیم آزادسازی وجه</p></div>
          <div className="absolute bg-[#edf7fe] h-[90px] left-[19px] overflow-clip rounded-[10px] text-right top-[81px] w-[680px]" data-node-id="2139:128" data-name="kpi-block">
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[662px] text-[#60758a] text-[10px] top-[22px] w-[644px]" data-node-id="2139:129"><p className="leading-[normal]" dir="auto">KPI مرحله</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[662px] text-[#17324d] text-[14px] top-[48px] w-[644px]" data-node-id="2139:130"><p className="leading-[normal]" dir="auto">شناسایی ۴۵۰ بهره‌مند واجد شرایط</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[662px] text-[#60758a] text-[10px] top-[73px] w-[644px]" data-node-id="2139:131"><p className="leading-[normal]" dir="auto">نتیجه و مستندات این KPI توسط آینه بررسی و تأیید شده است.</p></div>
          </div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[699px] text-[#17324d] text-[13px] text-right top-[199px] w-[680px]" data-node-id="2139:132"><p className="leading-[normal]" dir="auto">مستندات تأییدشده مرحله</p></div>
          <div className="absolute bg-[#f8fafc] h-[30px] left-[19px] overflow-clip rounded-[8px] top-[219px] w-[680px]" data-node-id="2139:133" data-name="document-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[660px] text-[#17324d] text-[11px] text-right top-[15px] w-[480px]" data-node-id="2139:134"><p className="leading-[normal]" dir="auto">گزارش اجرای مرحله</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#159455] text-[10px] top-[15px] w-[140px]" data-node-id="2139:135"><p className="leading-[normal]" dir="auto">تأیید شده</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[30px] left-[19px] overflow-clip rounded-[8px] top-[257px] w-[680px]" data-node-id="2139:136" data-name="document-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[660px] text-[#17324d] text-[11px] text-right top-[15px] w-[480px]" data-node-id="2139:137"><p className="leading-[normal]" dir="auto">فهرست بهره‌مندان</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#159455] text-[10px] top-[15px] w-[140px]" data-node-id="2139:138"><p className="leading-[normal]" dir="auto">تأیید شده</p></div></div>
          <div className="absolute bg-[#f8fafc] h-[30px] left-[19px] overflow-clip rounded-[8px] top-[295px] w-[680px]" data-node-id="2139:139" data-name="document-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[660px] text-[#17324d] text-[11px] text-right top-[15px] w-[480px]" data-node-id="2139:140"><p className="leading-[normal]" dir="auto">مستندات پشتیبان</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#159455] text-[10px] top-[15px] w-[140px]" data-node-id="2139:141"><p className="leading-[normal]" dir="auto">تأیید شده</p></div></div>
        </div>
        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[352px] left-[28px] overflow-clip rounded-[12px] top-[274px] w-[416px]" data-node-id="2139:142" data-name="release-decision">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[397px] text-[#17324d] text-[17px] text-right top-[29px] w-[380px]" data-node-id="2139:143"><p className="leading-[normal]" dir="auto">وضعیت درخواست</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[397px] text-[#60758a] text-[10px] text-right top-[54px] w-[380px]" data-node-id="2139:144"><p className="leading-[normal]" dir="auto">اطلاعات لازم برای اقدام کمیته امداد</p></div>
          <div className="[word-break:break-word] absolute bg-[#f8fafc] h-[42px] leading-[0] left-[17px] overflow-clip rounded-[8px] top-[83px] w-[380px]" data-node-id="2139:145" data-name="info-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[362px] text-[#60758a] text-[10px] text-right top-[20px] w-[150px]" data-node-id="2139:146"><p className="leading-[normal]" dir="auto">مرجع ارزیابی مرحله</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#17324d] text-[11px] top-[20px] w-[182px]" data-node-id="2139:147"><p className="leading-[normal]" dir="auto">خانه خلاق و نوآوری آینه</p></div></div>
          <div className="[word-break:break-word] absolute bg-[#f8fafc] h-[42px] leading-[0] left-[17px] overflow-clip rounded-[8px] top-[135px] w-[380px]" data-node-id="2139:148" data-name="info-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[362px] text-[#60758a] text-[10px] text-right top-[20px] w-[150px]" data-node-id="2139:149"><p className="leading-[normal]" dir="auto">نتیجه ارزیابی</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#159455] text-[11px] top-[20px] w-[182px]" data-node-id="2139:150"><p className="leading-[normal]" dir="auto">تأیید شده</p></div></div>
          <div className="[word-break:break-word] absolute bg-[#f8fafc] h-[42px] leading-[0] left-[17px] overflow-clip rounded-[8px] top-[187px] w-[380px]" data-node-id="2139:151" data-name="info-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[362px] text-[#60758a] text-[10px] text-right top-[20px] w-[150px]" data-node-id="2139:152"><p className="leading-[normal]" dir="auto">سهم این مرحله</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#17324d] text-[11px] top-[20px] w-[182px]" data-node-id="2139:153"><p className="leading-[normal]">۲۰٪</p></div></div>
          <div className="[word-break:break-word] absolute bg-[#fff7e6] h-[42px] leading-[0] left-[17px] overflow-clip rounded-[8px] top-[239px] w-[380px]" data-node-id="2139:154" data-name="info-row"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[362px] text-[#60758a] text-[10px] text-right top-[20px] w-[150px]" data-node-id="2139:155"><p className="leading-[normal]" dir="auto">وضعیت مالی</p></div><div className="-translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[18px] text-[#c27a10] text-[11px] top-[20px] w-[182px]" data-node-id="2139:156"><p className="leading-[normal]" dir="auto">در انتظار آزادسازی</p></div></div>
          <div className="absolute bg-[#edf7fe] h-[36px] left-[17px] overflow-clip rounded-[8px] top-[297px] w-[380px]" data-node-id="2139:157" data-name="scope-note"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[24px] justify-center leading-[0] left-[368px] text-[#17324d] text-[10px] text-right top-[18px] w-[356px]" data-node-id="2139:158"><p className="leading-[normal]" dir="auto">کمیته امداد ارزیابی محتوایی مرحله را تکرار نمی‌کند.</p></div></div>
        </div>
        <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[186px] left-[28px] overflow-clip rounded-[12px] top-[646px] w-[1160px]" data-node-id="2139:159" data-name="action-area">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[28px] justify-center leading-[0] left-[1139px] text-[#17324d] text-[17px] text-right top-[29px] w-[1120px]" data-node-id="2139:160"><p className="leading-[normal]" dir="auto">اقدام نهایی کمیته امداد</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[42px] justify-center leading-[0] left-[1139px] text-[#60758a] text-[11px] text-right top-[68px] w-[1120px]" data-node-id="2139:161"><p className="leading-[normal]" dir="auto">با ثبت تأیید، آزادسازی وجه این مرحله انجام‌شده ثبت می‌شود و نتیجه در سوابق پرداخت و پنل استارتاپ قابل مشاهده خواهد بود.</p></div>
          <div className="absolute bg-[#edf7fe] h-[46px] left-[19px] overflow-clip rounded-[8px] top-[99px] w-[680px]" data-node-id="2139:162" data-name="info"><div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[30px] justify-center leading-[0] left-[666px] text-[#17324d] text-[10px] text-right top-[23px] w-[652px]" data-node-id="2139:163"><p className="leading-[normal]" dir="auto">مبلغی در این صفحه نمایش داده نمی‌شود چون مبلغ مرحله در داده‌های موجود تعیین نشده است.</p></div></div>
          <Link to="/panel/emdad/release-requests" className="absolute bg-white block border border-[#e4ebf1] border-solid cursor-pointer h-[42px] left-[719px] overflow-clip rounded-[9px] top-[103px] w-[188px]" data-node-id="2139:164" data-name="back-button"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[26px] justify-center leading-[0] left-[93px] text-[#17324d] text-[12px] text-center top-[20px] w-[164px]" data-node-id="2139:165"><p className="leading-[normal]" dir="auto">بازگشت به درخواست‌ها</p></div></Link>
          <Link to="/panel/emdad/release-requests/success" className="absolute bg-[#2094e3] block cursor-pointer h-[42px] left-[927px] overflow-clip rounded-[9px] top-[103px] w-[212px]" data-node-id="2139:166" data-name="approve-release-button"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[26px] justify-center leading-[0] left-[106px] text-[12px] text-center text-white top-[21px] w-[188px]" data-node-id="2139:167"><p className="leading-[normal]" dir="auto">تأیید و آزادسازی وجه</p></div></Link>
        </div>
      </div>
      <div className="absolute bg-[#17324d] content-stretch flex flex-col gap-[10px] h-[900px] items-end left-[1216px] pb-[18px] pt-[20px] px-[16px] top-0 w-[224px]" data-node-id="2139:47" data-name="colored-sidebar">
        <div className="bg-white content-stretch flex h-[56px] items-center justify-end overflow-clip px-[10px] py-[8px] relative rounded-[12px] shrink-0 w-[192px]" data-node-id="2139:48" data-name="brand-logo"><div className="h-[40px] relative shrink-0 w-[118px]" data-node-id="2139:49" data-name="ChatGPT Image ۲۹ مرداد ۱۴۰۵، ۱۵_۱۶_۳۵ 1"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="" className="absolute h-full left-[5.28%] max-w-none top-0 w-[100.73%]" src={imgChatGptImage1} /></div></div></div>
        <div className="[word-break:break-word] content-stretch flex flex-col gap-[3px] h-[64px] items-start justify-end overflow-clip px-[8px] py-[7px] relative shrink-0 text-center w-[192px]" data-node-id="2139:50" data-name="panel-identity"><p className="font-sans font-medium h-[24px] leading-[normal] relative shrink-0 text-[13px] text-white w-[176px]" dir="auto" data-node-id="2139:51">سامانه ماه</p><div className="flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] relative shrink-0 text-[#d8e7f3] text-[10px] w-[176px]" data-node-id="2139:52"><p className="leading-[normal]" dir="auto">پنل کمیته امداد</p></div></div>
        <Link to="/panel/emdad" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2139:53" data-name="dashboard-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2139:54">داشبورد</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2139:55" data-name="dashboard-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2139:56" data-name="Frame"><div className="absolute inset-[11.11%]" data-node-id="2139:57" data-name="Group"><div className="absolute inset-[-5.71%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup} /></div></div></div></div></Link>
        <Link to="/panel/emdad/release-requests" className="bg-[#2094e3] content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2139:62" data-name="release-requests-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2139:63">درخواست‌های آزادسازی</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2139:64" data-name="users-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2139:65" data-name="Frame"><div className="absolute inset-[22.22%_13.89%_19.44%_13.89%]" data-node-id="2139:66" data-name="Group"><div className="absolute inset-[-7.62%_-6.15%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup1} /></div></div></div></div></Link>
        <Link to="/panel/emdad/article-172-approvals" className="block cursor-pointer h-[38px] overflow-clip relative rounded-[8px] shrink-0 w-[192px]" data-node-id="2139:69" data-name="article-172-approvals-nav"><p className="-translate-x-full [word-break:break-word] absolute font-sans font-normal leading-[normal] left-[152px] text-[#edf5fc] text-[12px] text-right top-[9.5px] w-[142px]" dir="auto" data-node-id="2139:70">تأیید گواهی ماده ۱۷۲</p><div className="absolute left-[162px] w-[18px] h-[18px] top-[10px]" data-node-id="2139:71" data-name="certificate-icon"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgCertificateIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2223:20" data-name="fund-synergy-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2223:21">هم‌افزایی صندوق</p><div className="relative shrink-0 w-[18px] h-[18px]" data-node-id="2226:16" data-name="fund-synergy-icon"><img alt="" className="absolute block inset-0 max-w-none w-full h-full" src={imgFundSynergyIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy/history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2237:179" data-name="fund-synergy-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2237:180">سوابق هم‌افزایی صندوق</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2237:181" data-name="project-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2237:182" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2237:183" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/payment-history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2139:75" data-name="payment-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2139:76">سوابق پرداخت</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2139:77" data-name="project-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2139:78" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2139:79" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/financial-reports" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2139:83" data-name="financial-reports-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2139:84">گزارش‌های مالی</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2139:85" data-name="milestone-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2139:86" data-name="Frame"><div className="absolute inset-[13.89%_11.11%]" data-node-id="2139:87" data-name="Group"><div className="absolute inset-[-6.15%_-5.71%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup3} /></div></div></div></div></Link>
        <Link to="/panel/emdad/fund-returns" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2382:414" data-name="fund-returns-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2382:415">منابع برگشتی صندوق</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2382:416" data-name="project-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2382:417" data-name="Frame"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]" data-node-id="2382:418" data-name="Group"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup2} /></div></div></div></div></Link>
        <div className="flex-[1_0_0] min-h-px relative w-[192px]" data-node-id="2139:100" data-name="sidebar-spacer" />
        <button type="button" className="bg-white content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end opacity-[0.96] overflow-clip px-[12px] relative rounded-[9px] shrink-0 w-[192px]" data-node-id="2139:101" data-name="logout-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[#17324d] text-[12px] text-right w-[142px]" dir="auto" data-node-id="2139:102">خروج از سیستم</p><div className="overflow-clip relative shrink-0 w-[18px] h-[18px]" data-node-id="2139:103" data-name="logout-icon"><div className="absolute left-0 overflow-clip w-[18px] h-[18px] top-0" data-node-id="2139:104" data-name="Frame"><div className="absolute inset-[16.67%_11.11%_16.67%_19.44%]" data-node-id="2139:105" data-name="Group"><div className="absolute inset-[-6.67%_-6.4%]"><img alt="" className="block max-w-none w-full h-full" src={imgGroup4} /></div></div></div></div></button>
      </div>
    </div>
  );
}
