import { Link } from "react-router-dom";
import "../index.css";

const imgChatGptImage1 = "/assets/emdad/dashboard/logo.png";
const imgEllipse = "/assets/emdad/payment-history/summary-success.svg";
const imgEllipse1 = "/assets/emdad/payment-history/summary-project.svg";
const imgEllipse2 = "/assets/emdad/payment-history/summary-closed.svg";
const imgGroup = "/assets/emdad/dashboard/group.svg";
const imgGroup1 = "/assets/emdad/dashboard/group1.svg";
const imgCertificateIcon = "/assets/emdad/dashboard/certificate-icon.svg";
const imgFundSynergyIcon = "/assets/emdad/dashboard/fund-synergy-icon.svg";
const imgGroup2 = "/assets/emdad/dashboard/group2.svg";
const imgGroup3 = "/assets/emdad/dashboard/group3.svg";
const imgGroup4 = "/assets/emdad/dashboard/group4.svg";

export default function EmdadPaymentHistory() {
  return (
    <div className="emdad-panel bg-[#f5f8fb] relative w-full h-full" data-node-id="2167:2" data-name="emdad-payment-history">
      <div className="absolute bg-[#f5f8fb] content-stretch flex flex-col gap-[16px] h-[900px] items-start left-0 overflow-clip px-[28px] py-[22px] top-0 w-[1216px]" data-node-id="2167:3" data-name="Main Content">
        <div className="[word-break:break-word] bg-white border border-[#e4ebf1] border-solid h-[72px] leading-[0] overflow-clip relative rounded-[12px] shrink-0 text-right w-full" data-node-id="2167:132" data-name="header">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[32px] justify-center left-[1131px] text-[#17324d] text-[22px] top-[23px] w-[432px]"><p className="leading-[normal]" dir="auto">سوابق پرداخت</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[1131px] text-[#60758a] text-[11px] top-[49px] w-[652px]"><p className="leading-[normal]" dir="auto">آزادسازی‌های وجه ثبت‌شده توسط کمیته امداد برای مراحل تأییدشده</p></div>
        </div>

        <div className="h-[92px] overflow-clip relative shrink-0 w-full" data-node-id="2167:135" data-name="summary-row">
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[92px] left-0 overflow-clip rounded-[12px] top-0 w-[372px]" data-node-id="2167:136" data-name="summary-card">
            <div className="absolute left-[17px] size-[8px] top-[17px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse} /></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[351px] text-[#60758a] text-[12px] text-right top-[19px] w-[304px]"><p className="leading-[normal]" dir="auto">آزادسازی‌های ثبت‌شده</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[351px] text-[#159455] text-[22px] text-right top-[47px] w-[334px]"><p className="leading-[normal]">۱</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[351px] text-[#60758a] text-[10px] text-right top-[72px] w-[334px]"><p className="leading-[normal]" dir="auto">رکورد نهایی ثبت‌شده</p></div>
          </div>
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[92px] left-[394px] overflow-clip rounded-[12px] top-0 w-[372px]" data-node-id="2167:141" data-name="summary-card">
            <div className="absolute left-[17px] size-[8px] top-[17px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse1} /></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[351px] text-[#60758a] text-[12px] text-right top-[19px] w-[304px]"><p className="leading-[normal]" dir="auto">پروژه‌های دارای سابقه</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[351px] text-[#2094e3] text-[22px] text-right top-[47px] w-[334px]"><p className="leading-[normal]">۱</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[351px] text-[#60758a] text-[10px] text-right top-[72px] w-[334px]"><p className="leading-[normal]" dir="auto">پروژه با سابقه آزادسازی</p></div>
          </div>
          <div className="absolute bg-white border border-[#e4ebf1] border-solid h-[92px] left-[788px] overflow-clip rounded-[12px] top-0 w-[372px]" data-node-id="2167:146" data-name="summary-card">
            <div className="absolute left-[17px] size-[8px] top-[17px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse2} /></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[351px] text-[#60758a] text-[12px] text-right top-[19px] w-[304px]"><p className="leading-[normal]" dir="auto">مراحل بسته‌شده مالی</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[351px] text-[#17324d] text-[22px] text-right top-[47px] w-[334px]"><p className="leading-[normal]">۱</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[351px] text-[#60758a] text-[10px] text-right top-[72px] w-[334px]"><p className="leading-[normal]" dir="auto">مرحله با ثبت نهایی آزادسازی</p></div>
          </div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[74px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2167:151" data-name="toolbar">
          <button type="button" className="absolute bg-[#f5f8fb] block border border-[#e4ebf1] border-solid cursor-pointer h-[42px] left-[645px] overflow-clip rounded-[8px] top-[15px] w-[486px]" data-node-id="2167:152" data-name="search"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[469px] text-[#60758a] text-[11px] text-right top-[20px] w-[454px]"><p className="leading-[normal]" dir="auto">جستجو در پروژه یا مرحله</p></div></button>
          <button type="button" className="absolute bg-white block border border-[#e4ebf1] border-solid cursor-pointer h-[42px] left-[413px] overflow-clip rounded-[8px] top-[15px] w-[212px]" data-node-id="2167:154" data-name="status-filter"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[24px] justify-center left-[195px] text-[#17324d] text-[11px] text-right top-[20px] w-[180px]"><p className="leading-[normal]" dir="auto">همه وضعیت‌ها</p></div></button>
          <div className="absolute bg-[#ebf6fd] h-[28px] left-[19px] overflow-clip rounded-[14px] top-[22px] w-[112px]" data-node-id="2167:156" data-name="count-pill"><div className="-translate-x-1/2 -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[20px] justify-center left-[56px] text-[#2094e3] text-[11px] text-center top-[14px] w-[96px]"><p className="leading-[normal]" dir="auto">۱ رکورد</p></div></div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[296px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2167:158" data-name="payment-history-table">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[1131px] text-[#17324d] text-[18px] text-right top-[29px] w-[372px]"><p className="leading-[normal]" dir="auto">سوابق آزادسازی وجه</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[1131px] text-[#60758a] text-[10px] text-right top-[52px] w-[482px]"><p className="leading-[normal]" dir="auto">رکوردهای نهایی پس از ثبت آزادسازی توسط کمیته امداد</p></div>
          <div className="absolute bg-[#f5f8fb] font-sans font-medium h-[36px] left-[19px] overflow-clip rounded-[8px] text-[#60758a] text-[10px] text-right top-[81px] w-[1120px]" data-node-id="2167:161" data-name="table-header">
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[1104px] top-[18px] w-[74px]"><p className="leading-[normal]" dir="auto">ردیف</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[1030px] top-[18px] w-[300px]"><p className="leading-[normal]" dir="auto">پروژه</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[730px] top-[18px] w-[205px]"><p className="leading-[normal]" dir="auto">مرحله</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[525px] top-[18px] w-[120px]"><p className="leading-[normal]" dir="auto">سهم مرحله</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[345px] top-[18px] w-[125px]"><p className="leading-[normal]" dir="auto">وضعیت</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col h-[22px] justify-center left-[220px] top-[18px] w-[200px]"><p className="leading-[normal]" dir="auto">اقدام</p></div>
          </div>
          <div className="absolute bg-[#f5f8fb] border border-[#e4ebf1] border-solid h-[64px] left-[19px] overflow-clip rounded-[8px] top-[129px] w-[1120px]" data-node-id="2167:168" data-name="payment-history-row">
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[44px] justify-center left-[1103px] text-[#17324d] text-[12px] text-right top-[31px] w-[74px]"><p className="leading-[normal]">۱</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[22px] justify-center left-[1029px] text-[#17324d] text-[12px] text-right top-[18px] w-[300px]"><p className="leading-[normal]" dir="auto">اشتغال زنان روستایی</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[1029px] text-[#60758a] text-[10px] text-right top-[40px] w-[300px]"><p className="leading-[normal]" dir="auto">گلستان · کسب‌وکار و اشتغال</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[40px] justify-center left-[729px] text-[#17324d] text-[11px] text-right top-[29px] w-[205px]"><p className="leading-[normal]" dir="auto">شناسایی و ارزیابی</p></div>
            <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[40px] justify-center left-[524px] text-[#17324d] text-[12px] text-right top-[29px] w-[120px]"><p className="leading-[normal]">۲۰٪</p></div>
            <div className="absolute bg-[#e8f7ef] h-[28px] left-[254px] overflow-clip rounded-[14px] top-[17px] w-[132px]" data-node-id="2167:174" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[20px] justify-center left-[66px] text-[#159455] text-[11px] text-center top-[14px] w-[116px]"><p className="leading-[normal]" dir="auto">ثبت آزادسازی</p></div></div>
            <Link to="/panel/emdad/payment-history/detail" className="absolute bg-[#2094e3] border border-[#2094e3] border-solid h-[38px] left-[35px] overflow-clip rounded-[8px] top-[12px] w-[150px]" data-node-id="2167:176" data-name="detail-button"><div className="-translate-x-1/2 -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[74px] text-[12px] text-center text-white top-[18px] w-[130px]"><p className="leading-[normal]" dir="auto">مشاهده جزئیات</p></div></Link>
          </div>
          <div className="absolute bg-[#f5f8fb] content-stretch flex h-[40px] items-center justify-between left-[19px] overflow-clip px-[10px] rounded-[8px] top-[205px] w-[1120px]" data-node-id="2197:20" data-name="pagination-footer">
            <div className="content-stretch flex gap-[8px] h-[30px] items-center overflow-clip relative shrink-0" data-node-id="2197:21" data-name="pagination-controls">
              <button type="button" disabled className="bg-white border border-[#e4ebf1] border-solid content-stretch cursor-default flex h-[30px] items-center justify-center opacity-50 overflow-clip relative rounded-[7px] shrink-0 w-[52px]"><span className="font-sans font-medium text-[#17324d] text-[10px]">بعدی</span></button>
              <div className="bg-[#2094e3] content-stretch flex items-center justify-center overflow-clip relative rounded-[7px] shrink-0 size-[30px]"><span className="font-sans font-medium text-[10px] text-white">۱</span></div>
              <button type="button" disabled className="bg-white border border-[#e4ebf1] border-solid content-stretch cursor-default flex h-[30px] items-center justify-center opacity-50 overflow-clip relative rounded-[7px] shrink-0 w-[52px]"><span className="font-sans font-medium text-[#17324d] text-[10px]">قبلی</span></button>
            </div>
            <div className="flex flex-col font-sans font-normal h-[22px] justify-center text-[#60758a] text-[10px] text-right w-[240px]"><p className="leading-[normal]" dir="auto">نمایش ۱ تا ۱ از ۱</p></div>
          </div>
          <div className="absolute bg-[#ebf6fd] h-[28px] left-[19px] overflow-clip rounded-[8px] top-[253px] w-[1120px]" data-node-id="2167:178" data-name="table-note"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[20px] justify-center left-[1104px] text-[#60758a] text-[10px] text-right top-[14px] w-[1088px]"><p className="leading-[normal]" dir="auto">مبلغ فقط در صورت وجود رکورد مالی ثبت‌شده نمایش داده می‌شود؛ در این سابقه مبلغی ثبت نشده است.</p></div></div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[104px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2167:180" data-name="history-info">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[28px] justify-center left-[1131px] text-[#17324d] text-[16px] text-right top-[27px] w-[332px]"><p className="leading-[normal]" dir="auto">قاعده ثبت در سوابق پرداخت</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[38px] justify-center left-[1131px] text-[#60758a] text-[11px] text-right top-[62px] w-[972px]"><p className="leading-[normal]" dir="auto">هر رکورد زمانی وارد این بخش می‌شود که مرحله توسط آینه تأیید شده باشد و آزادسازی وجه آن توسط کمیته امداد ثبت نهایی شده باشد.</p></div>
          <div className="absolute bg-[#e8f7ef] h-[28px] left-[19px] overflow-clip rounded-[14px] top-[61px] w-[116px]" data-node-id="2167:183" data-name="status-pill"><div className="-translate-x-1/2 -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[20px] justify-center left-[58px] text-[#159455] text-[11px] text-center top-[14px] w-[100px]"><p className="leading-[normal]" dir="auto">ثبت نهایی</p></div></div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[92px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2167:185" data-name="lower-actions">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[1131px] text-[#17324d] text-[14px] text-right top-[23px] w-[282px]"><p className="leading-[normal]" dir="auto">ادامه مدیریت مالی</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[22px] justify-center left-[1131px] text-[#60758a] text-[10px] text-right top-[48px] w-[682px]"><p className="leading-[normal]" dir="auto">برای مشاهده درخواست‌های در انتظار آزادسازی به فهرست درخواست‌ها برگردید.</p></div>
          <Link to="/panel/emdad/release-requests" className="absolute bg-white border border-[#e4ebf1] border-solid h-[38px] left-[19px] overflow-clip rounded-[8px] top-[45px] w-[190px]" data-node-id="2167:188" data-name="release-requests-button"><div className="-translate-x-1/2 -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[94px] text-[#17324d] text-[12px] text-center top-[18px] w-[170px]"><p className="leading-[normal]" dir="auto">درخواست‌های آزادسازی</p></div></Link>
        </div>
      </div>

      <div className="absolute bg-[#17324d] content-stretch flex flex-col gap-[10px] h-[900px] items-end left-[1216px] pb-[18px] pt-[20px] px-[16px] top-0 w-[224px]" data-node-id="2167:70" data-name="colored-sidebar">
        <div className="bg-white content-stretch flex h-[56px] items-center justify-end overflow-clip px-[10px] py-[8px] relative rounded-[12px] shrink-0 w-[192px]" data-node-id="2167:71" data-name="brand-logo"><div className="h-[40px] relative shrink-0 w-[118px]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="" className="absolute h-full left-[5.28%] max-w-none top-0 w-[100.73%]" src={imgChatGptImage1} /></div></div></div>
        <div className="content-stretch flex flex-col gap-[3px] h-[64px] items-start justify-end overflow-clip px-[8px] py-[7px] relative shrink-0 text-center w-[192px]" data-node-id="2167:73" data-name="panel-identity"><p className="font-sans font-medium h-[24px] leading-[normal] relative shrink-0 text-[13px] text-white w-[176px]" dir="auto">سامانه ماه</p><div className="flex flex-col font-sans font-normal h-[18px] justify-center text-[#d8e7f3] text-[10px] w-[176px]"><p className="leading-[normal]" dir="auto">پنل کمیته امداد</p></div></div>
        <Link to="/panel/emdad" className="content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2167:76" data-name="dashboard-nav"><p className="font-sans font-medium leading-[normal] relative shrink-0 text-[12px] text-right text-white w-[142px]">داشبورد</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[11.11%]"><div className="absolute inset-[-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup} /></div></div></div></Link>
        <Link to="/panel/emdad/release-requests" className="content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2167:85" data-name="release-requests-nav"><p className="font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]">درخواست‌های آزادسازی</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[22.22%_13.89%_19.44%_13.89%]"><div className="absolute inset-[-7.62%_-6.15%]"><img alt="" className="block max-w-none size-full" src={imgGroup1} /></div></div></div></Link>
        <Link to="/panel/emdad/article172-approvals" className="block h-[38px] overflow-clip relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2167:92" data-name="article-172-approvals-nav"><p className="-translate-x-full absolute font-sans font-normal leading-[normal] left-[152px] text-[12px] text-right text-white top-[9.5px] w-[142px]">تأیید گواهی ماده ۱۷۲</p><div className="absolute left-[162px] size-[18px] top-[10px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgCertificateIcon} /></div></Link>
        <button type="button" className="content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2223:65" data-name="fund-synergy-nav"><p className="font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]">هم‌افزایی صندوق</p><div className="relative shrink-0 size-[18px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgFundSynergyIcon} /></div></button>
        <button type="button" className="content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2237:219" data-name="fund-synergy-history-nav"><p className="font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]">سوابق هم‌افزایی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></button>
        <div className="bg-[#2094e3] content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2167:98" data-name="payment-history-nav"><p className="font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]">سوابق پرداخت</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div>
        <button type="button" className="content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2167:106" data-name="financial-reports-nav"><p className="font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]">گزارش‌های مالی</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[13.89%_11.11%]"><div className="absolute inset-[-6.15%_-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup3} /></div></div></div></button>
        <button type="button" className="content-stretch flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2382:454" data-name="fund-returns-nav"><p className="font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]">منابع برگشتی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></button>
        <div className="flex-[1_0_0] min-h-px relative w-[192px]" data-node-id="2167:123" data-name="sidebar-spacer" />
        <button type="button" className="bg-white content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end opacity-96 overflow-clip px-[12px] relative rounded-[9px] shrink-0 w-[192px]" data-node-id="2167:124" data-name="logout-nav"><p className="font-sans font-medium leading-[normal] relative shrink-0 text-[#17324d] text-[12px] text-right w-[142px]">خروج از سیستم</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute inset-[16.67%_11.11%_16.67%_19.44%]"><div className="absolute inset-[-6.67%_-6.4%]"><img alt="" className="block max-w-none size-full" src={imgGroup4} /></div></div></div></button>
      </div>
    </div>
  );
}
