import React from "react";
import "./index.css";

function Skeleton({className}:{className:string}){return <div className={"skeleton rounded-md "+className}/>}
function Sidebar(){
 const groups=[["محتوا",["داشبورد","همه محتواها","اخبار","صفحات سایت","صفحه اصلی","سؤالات متداول"]],["انتشار",["رسانه‌ها","منو و Footer","بازبینی و پیش‌نمایش"]],["مدیریت",["کاربران و نقش‌ها","گزارش فعالیت‌ها","تنظیمات CMS"]]];
 return <aside className="absolute right-0 top-0 flex h-[1584px] w-[264px] flex-col border-l border-[#e4ebf1] bg-white px-4 py-6"><img className="mb-5 h-[46px] w-[137px] self-center object-contain" src="/assets/codia/DYXETeHo5p.png" alt="سامانه ماه"/><div className="mb-6 flex items-center gap-3 rounded-xl bg-[#f6f9fb] p-3"><img className="h-9 w-9 rounded-full object-cover" src="/assets/codia/kS9x4tmGk5.png" alt="نگار حسینی"/><div><b className="text-[13px]">نگار حسینی</b><p className="text-[11px] text-[#60758a]">مدیر محتوا <span className="mr-2 rounded bg-[#eaf5fd] px-2 py-1 text-[#2094e3]">CMS</span></p></div></div>{groups.map(([title,items])=><div className="mb-5" key={title as string}><h2 className="mb-2 px-3 text-[11px] font-bold text-[#60758a]">{title as string}</h2>{(items as string[]).map(x=><div className={"flex items-center gap-3 rounded-lg px-3 py-3 text-[14px] "+(x==="اخبار"?"bg-[#eaf5fd] font-bold text-[#2094e3]":"text-[#60758a]")} key={x}><span className="w-5 text-center">◇</span>{x}</div>)}</div>)}<button className="mt-auto rounded-xl bg-[#2094e3] py-3 font-bold text-white">خروج از سیستم</button></aside>
}
function Header(){return <header className="flex h-20 items-center justify-between border-b border-[#e4ebf1]"><div className="flex items-center gap-4"><img className="h-9 w-9 rounded-full object-cover" src="/assets/codia/kS9x4tmGk5.png" alt="نگار حسینی"/><div><b className="text-[13px]">نگار حسینی</b><p className="text-[11px] text-[#60758a]">مدیر محتوا</p></div><button className="rounded-lg border border-[#dbe4ec] p-2">؟</button><button className="relative rounded-lg border border-[#dbe4ec] p-2">♧<span className="absolute -right-1 -top-2 rounded-full bg-[#ef4444] px-1.5 text-[10px] text-white">۵</span></button><div className="rounded-lg border border-[#dbe4ec] px-3 py-2 text-[13px]">▣ یکشنبه، ۲۶ مرداد ۱۴۰۵</div></div><label className="flex h-10 w-[380px] items-center rounded-xl border border-[#dbe4ec] bg-white px-4 text-[13px] text-[#60758a]">⌕<input className="mr-2 w-full" placeholder="جست‌وجوی عنوان، نویسنده یا نوع محتوا..."/></label></header>}
export default function Main(){return <div className="main-container relative h-[1584px] w-[1440px] bg-[#f4f6f8] text-[#17324d]" dir="rtl"><Sidebar/><div className="mr-[264px] px-10"><Header/><div className="flex items-center justify-between py-7"><div className="flex gap-3"><Skeleton className="h-10 w-[120px]"/><Skeleton className="h-10 w-[120px]"/></div><div className="space-y-2"><Skeleton className="h-4 w-[200px]"/><Skeleton className="mr-auto h-3 w-[100px]"/></div></div><main className="grid grid-cols-[400px_1fr] gap-6"><aside className="space-y-6"><div className="rounded-2xl border border-[#dbe4ec] bg-white p-5"><Skeleton className="mb-4 h-4 w-[100px]"/><div className="h-px bg-[#dbe4ec]"/><Skeleton className="mt-4 h-10 w-full"/><Skeleton className="mt-4 h-10 w-full"/></div><div className="rounded-2xl border border-[#dbe4ec] bg-white p-5"><Skeleton className="mb-4 h-4 w-[100px]"/><div className="h-px bg-[#dbe4ec]"/><Skeleton className="mt-4 h-10 w-full"/><Skeleton className="mt-4 h-10 w-full"/></div></aside><section className="space-y-6"><div className="rounded-2xl border border-[#dbe4ec] bg-white p-6"><Skeleton className="h-4 w-[100px]"/><Skeleton className="mt-3 h-11 w-full"/><Skeleton className="mt-6 h-4 w-[100px]"/><Skeleton className="mt-3 h-[170px] w-full"/></div><div className="rounded-2xl border border-[#dbe4ec] bg-white p-6"><Skeleton className="h-4 w-[100px]"/><Skeleton className="mt-4 h-[120px] w-full"/></div><div className="rounded-2xl border border-[#dbe4ec] bg-white p-6"><Skeleton className="h-4 w-[100px]"/><Skeleton className="mt-4 h-[300px] w-full"/></div></section></main></div></div>}
