import React from "react";
import "./index.css";

type Section = { title: string; intro?: string; bullets?: string[]; note?: string };
const sections: Section[] = [
  {title:"۱. درباره این سیاست",intro:"سامانه ماه برای ارائه بهینه خدمات خود، از جمله نمایش شفاف پروژه‌ها، ثبت و پیگیری مشارکت‌های اجتماعی، ایجاد حساب کاربری سازمانی، ثبت‌نام استارتاپ‌ها، پیگیری دقیق فرآیندهای پرداخت، گزارش‌دهی دوره‌ای اثر و پاسخ‌گویی پشتیبانی، برخی اطلاعات کاربران را دریافت و پردازش می‌کند. این سند چارچوب دریافت، پردازش، استفاده، حفاظت و نگهداری اطلاعات کاربران را تشریح می‌کند."},
  {title:"۲. دامنه کاربرد",intro:"این سیاست کلیه کاربرانی را که به هر نحوی با سامانه ماه تعامل دارند تحت پوشش قرار می‌دهد:",bullets:["بازدیدکنندگان و وب‌گردان عادی وب‌سایت عمومی سامانه ماه","مشارکت‌کنندگان حقیقی که اقدام به حمایت مالی از پروژه‌ها می‌کنند","نمایندگان حقوقی، مدیران و رابطین شرکت‌ها و سازمان‌های همکار","اعضای کلیدی، توسعه‌دهندگان و نمایندگان رسمی استارتاپ‌های متقاضی","کاربران و ناظران پنل‌های تخصصی خانه خلاق و نهادهای حمایتی","افرادی که از طریق فرم‌های آنلاین درخواست پشتیبانی ثبت می‌کنند"],note:"ممکن است برای برخی خدمات تخصصی یا مراحل ویژه، اطلاعیه‌ها یا شرایط تکمیلی حریم خصوصی به شما نمایش داده شود."},
  {title:"۳. اطلاعات دریافتی",intro:"اطلاعات متناسب با نوع کاربر و خدمت دریافت می‌شوند.",bullets:["افراد حقیقی: شماره تلفن همراه، پروژه انتخاب‌شده، مبلغ پرداختی، شماره مرجع بانکی و تاریخچه پشتیبانی","شرکت‌ها و سازمان‌ها: شناسه ملی، شماره ثبت، کد اقتصادی، مدارک تأسیس، مشخصات نماینده و سوابق درخواست گواهی ماده ۱۷۲","استارتاپ‌ها: اطلاعات حقوقی، مشخصات اعضای کلیدی، توضیحات فنی محصول، گزارش‌های پیشرفت و مستندات KPI","پشتیبانی و فنی: نام، ایمیل، شرح درخواست، فایل‌های پیوست، آدرس IP، نوع مرورگر، سیستم‌عامل و لاگ خطاها"],note:"افراد حقیقی برای انجام مشارکت عمومی در پروژه‌ها الزامی به ایجاد حساب کاربری دائمی در سامانه ندارند."},
  {title:"۴. نحوه دریافت اطلاعات",intro:"سامانه ماه اطلاعات را عمدتاً به روش‌های مستقیم و در موارد خاص از طریق ابزارهای خودکار دریافت می‌کند:",bullets:["ورود مستقیم اطلاعات توسط خود کاربر در فرم‌های مشارکت یا ثبت‌نام","ثبت سوابق تراکنش از طریق وب‌سرویس‌های امن درگاه‌های بانکی همکار","بارگذاری مستندات و گزارش‌های پیشرفت توسط استارتاپ‌ها","جمع‌آوری کوکی‌های مرورگر و داده‌های لاگ فنی برای بهبود عملکرد و امنیت"]},
  {title:"۵. اهداف پردازش",intro:"پردازش داده‌های دریافتی منحصراً برای اهداف زیر انجام می‌شود:",bullets:["احراز هویت کاربران و نمایندگان قانونی","تخصیص دقیق مبالغ به پروژه‌های انتخابی","تسهیل پرداخت مرحله‌ای بر اساس تأیید شاخص‌های KPI","ارسال پیامک کد پیگیری، وضعیت واریز و گزارش پیشرفت","ارائه آمارهای تجمیعی به دستگاه‌های نظارتی","تولید مستندات قانونی گواهی ماده ۱۷۲","شناسایی رفتارهای مشکوک و بهبود امنیت فنی"],note:"اطلاعات کاربران خارج از اهداف تشریح‌شده و بدون کسب رضایت صریح مجدد پردازش نخواهد شد."},
  {title:"۶. اطلاعات پرداخت",intro:"کلیه فرآیندهای مالی توسط درگاه‌های پرداخت تحت نظارت شبکه شاپرک انجام می‌شود.",bullets:["سامانه ماه اطلاعات حساسی نظیر رمز دوم، CVV۲ یا رمز پویا را ذخیره نمی‌کند.","۱۰۰٪ مبالغ مستقیماً به حساب‌های رسمی و امانی کمیته امداد امام خمینی (ره) واریز می‌گردد."],note:"هشدار امنیتی: اطلاعات بانکی حساس خود را در فرم‌های عمومی یا بخش توضیحات تیکت پشتیبانی وارد نکنید."},
  {title:"۷. اشتراک‌گذاری اطلاعات",intro:"اطلاعات هویتی و محرمانه به‌صورت پیش‌فرض محافظت‌شده‌اند و صرفاً در شرایط زیر به اشتراک گذاشته می‌شوند:",bullets:["ارسال مستندات تراکنش به کمیته امداد برای ثبت و تأیید حساب","ارائه اطلاعات فنی پروژه‌ها به کارشناسان رسمی خانه خلاق برای صحه‌گذاری KPI","پاسخ به دستورهای رسمی مقامات قضایی ذی‌صلاح"],note:"سامانه ماه اطلاعات شما را برای اهداف تبلیغاتی در اختیار شرکت‌های ثالث قرار نمی‌دهد."},
  {title:"۸. اطلاعات عمومی پروژه‌ها",intro:"برای شفافیت عمومی، نام پروژه، مکان اجرا، پیشرفت مالی، استارتاپ مجری و نتایج تجمیعی KPI منتشر می‌شوند. اطلاعات هویتی و شماره تماس مشارکت‌کنندگان، مدارک مالی تفصیلی شرکت‌ها، رزومه‌های خصوصی و کدهای ملی محرمانه باقی می‌مانند."},
  {title:"۹. نگهداری اطلاعات",intro:"اطلاعات تنها تا زمانی که برای ایفای اهداف قانونی سامانه و ارائه گزارش‌های دقیق موردنیاز باشد نگهداری می‌شوند. این بازه تابع مقررات مالی، مالیاتی و استانداردهای آرشیوبندی حاکمیتی است."},
  {title:"۱۰. امنیت",intro:"حفظ حریم خصوصی و امنیت داده‌ها اولویت درجه اول سامانه ماه است.",bullets:["رمزنگاری ارتباطات و تبادل داده با پروتکل امن SSL/TLS","کنترل دسترسی چندلایه برای پرسنل فنی و اداری","تست‌های دوره‌ای نفوذپذیری و پایش مداوم سیستم‌ها"],note:"هیچ فناوری امنیتی تضمین مطلق ۱۰۰٪ ایجاد نمی‌کند؛ حفاظت از کدهای تأیید به ارتقای امنیت کمک می‌کند."},
  {title:"۱۱. حقوق و درخواست‌های کاربران",intro:"شما همواره بر داده‌های خود کنترل دارید.",bullets:["حق آگاهی از ماهیت، نوع و اهداف اطلاعات پردازش‌شده","حق اصلاح مشخصات و ویرایش مدارک سازمانی یا استارتاپی","حق درخواست غیرفعال‌سازی حساب سازمانی"]},
  {title:"۱۲. کوکی‌ها و داده‌های فنی",intro:"کوکی‌ها برای حفظ نشست کاری، یادآوری ترجیحات، سنجش عملکرد و افزایش امنیت استفاده می‌شوند.",bullets:["کوکی‌های ضروری برای ورود و پرداخت","کوکی‌های امنیتی برای شناسایی تلاش‌های نامعتبر","کوکی‌های عملکردی برای حفظ اولویت‌های نمایش","کوکی‌های تحلیلی برای درک ناشناس ترافیک صفحات"]},
  {title:"۱۳. حفاظت از اطلاعات جامعه هدف",intro:"جزییات هویتی، آدرس‌های دقیق مسکونی و وضعیت مددجویی افراد بهره‌مند عمومی نمی‌شود و تحت پروتکل‌های امنیتی ویژه نگهداری خواهد شد. گزارش‌های عمومی بر شاخص‌های تجمیعی و خروجی‌های اثر تمرکز دارند."},
  {title:"۱۴. تغییرات این سیاست",intro:"ممکن است با تغییر قوانین یا اضافه شدن ویژگی‌های جدید، این سیاست تغییر کند. آخرین نسخه و تاریخ اجرای آن همواره در همین صفحه در دسترس است."},
  {title:"ارتباط با ما",intro:"در صورت داشتن سؤال، ابهام، پیشنهاد یا درخواست رسمی درباره این سیاست، تیم پشتیبانی ماه آماده پاسخ‌گویی است."}
];

function Header(){return <><header className="flex pt-[16px] pr-[120px] pb-[16px] pl-[120px] justify-between items-center self-stretch shrink-0 flex-nowrap bg-[#fff] border-solid border-t border-t-[#e4ebf1] relative" dir="ltr"><div className="flex w-[384px] gap-[12px] justify-end items-center shrink-0 flex-nowrap relative"><a className="flex w-[120px] h-[44px] pt-[11px] pr-[20px] pb-[11px] pl-[20px] justify-center items-center shrink-0 flex-nowrap bg-[#fff] rounded-[12px] border-solid border-[1.5px] border-[#2094e3] text-[14px] font-medium leading-[22px] text-[#2094e3] text-center whitespace-nowrap" href="/auth">ورود کاربران</a><a className="flex w-[120px] h-[44px] pt-[11px] pr-[20px] pb-[11px] pl-[20px] justify-center items-center shrink-0 flex-nowrap bg-[#fff] rounded-[12px] border-solid border-[1.5px] border-[#2094e3] text-[14px] font-medium leading-[22px] text-[#2094e3] text-center whitespace-nowrap" href="/participation/track">پیگیری مشارکت</a><a className="flex w-[120px] h-[44px] pt-[11px] pr-[20px] pb-[11px] pl-[20px] gap-[8px] justify-center items-center shrink-0 flex-nowrap bg-[#2094e3] rounded-[12px] text-[14px] font-medium leading-[22px] text-[#fff] text-center whitespace-nowrap" href="/projects">شروع مشارکت</a></div><div className="flex w-[630px] gap-[40px] justify-end items-center shrink-0 flex-nowrap relative"><nav className="flex w-[453px] gap-[24px] items-center shrink-0 flex-nowrap relative" aria-label="ناوبری اصلی"><a className="flex w-[45px] h-[22px] justify-end items-start shrink-0 basis-auto text-[14px] font-medium leading-[21.875px] text-[#17324d] text-right whitespace-nowrap" href="/about">درباره ما</a><a className="flex w-[60px] h-[22px] justify-end items-start shrink-0 basis-auto text-[14px] font-medium leading-[21.875px] text-[#17324d] text-right whitespace-nowrap" href="/contact">تماس با ما</a><a className="flex w-[52px] h-[22px] justify-end items-start shrink-0 basis-auto text-[14px] font-medium leading-[21.875px] text-[#17324d] text-right whitespace-nowrap" href="/companies">شرکت‌ها</a><a className="flex w-[66px] h-[22px] justify-end items-start shrink-0 basis-auto text-[14px] font-medium leading-[21.875px] text-[#17324d] text-right whitespace-nowrap" href="/startups">استارتاپ‌ها</a><a className="flex w-[41px] h-[22px] justify-end items-start shrink-0 basis-auto text-[14px] font-medium leading-[21.875px] text-[#17324d] text-right whitespace-nowrap" href="/projects">پروژه‌ها</a><a className="flex w-[69px] h-[22px] justify-end items-start shrink-0 basis-auto text-[14px] font-medium leading-[21.875px] text-[#17324d] text-right whitespace-nowrap" href="/">صفحه اصلی</a></nav><a className="w-[137px] h-[46px] shrink-0 bg-[url(/assets/codia/TMHBH1Usk6.png)] bg-cover bg-no-repeat relative" href="/" aria-label="صفحه اصلی" /></div></header><div className="h-[46px] px-[120px] pt-5 text-[14px] text-[#60758a]">صفحه اصلی / سیاست حریم خصوصی</div></>;}
function Footer(){return <footer className="bg-[#111e30] px-[120px] pb-7 pt-14 text-white"><div className="grid grid-cols-[1.7fr_1fr_1fr_1fr] gap-16"><div><img className="mb-5 h-[50px] w-[150px] object-contain brightness-0 invert" src="/assets/codia/j0Pvw1w6QL.png" alt="سامانه ماه"/><p className="text-[13px] leading-7 text-[#c7d2dc]">سامانه مشارکت در پروژه‌های دارای اثر اجتماعی با مسیر مالی شفاف و اثر قابل‌اندازه‌گیری.</p></div><div><b>دسترسی سریع</b><p className="mt-3 text-[13px] leading-8 text-[#c7d2dc]">پروژه‌ها<br/>برای شرکت‌ها<br/>نحوه مشارکت<br/>ثبت‌نام استارتاپ</p></div><div><b>پشتیبانی</b><p className="mt-3 text-[13px] leading-8 text-[#c7d2dc]">تماس با ما<br/>سؤالات متداول<br/>پیگیری مشارکت</p></div><div><b>حقوقی</b><p className="mt-3 text-[13px] leading-8 text-[#c7d2dc]">قوانین و مقررات<br/>حریم خصوصی<br/>سیاست بازپرداخت</p></div></div><div className="mt-9 border-t border-[#304154] pt-5 text-center text-[12px] text-[#93a5b7]">تمامی حقوق برای سامانه ماه محفوظ است • ۱۴۰۵</div></footer>;}

export default function Main(){return <div className="main-container w-[1440px] bg-[#fcfbf8] text-[#17324d]" dir="rtl"><Header/>
  <section className="px-[120px] pb-12 pt-10 text-center"><h1 className="text-[32px] font-extrabold">سیاست حریم خصوصی سامانه ماه</h1><p className="mx-auto mt-4 max-w-[850px] text-[15px] leading-7 text-[#60758a]">در این صفحه توضیح می‌دهیم چه اطلاعاتی در سامانه ماه دریافت و پردازش می‌شود و کاربران چگونه می‌توانند درخواست‌های مرتبط با اطلاعات خود را ثبت کنند.</p><div className="mt-8 flex items-center justify-center gap-4 text-[13px]"><span>نسخه سند: نسخه تأییدشده جاری</span><span>•</span><span>آخرین به‌روزرسانی: ۲۴ مرداد ۱۴۰۵</span><span>•</span><span>تاریخ اجرا: ۱ شهریور ۱۴۰۵</span><button className="mr-4 rounded-lg border border-[#dbe4ec] px-3 py-2">چاپ</button><button className="rounded-lg border border-[#dbe4ec] px-3 py-2">دریافت نسخه PDF</button><button className="rounded-lg border border-[#dbe4ec] px-3 py-2">کپی لینک</button></div></section>
  <section className="bg-white px-[120px] py-8"><div className="rounded-[22px] border border-[#dbe4ec] bg-[#f6f9fb] p-8"><h2 className="mb-5 text-[20px] font-bold">خلاصه سیاست حریم خصوصی</h2><div className="grid grid-cols-2 gap-4">{["فقط اطلاعات اساسی و موردنیاز برای ارائه خدمات شفاف ماه دریافت می‌شوند.","اطلاعات عمومی و محرمانه به شکل ساختاریافته از یکدیگر تفکیک می‌شوند.","اطلاعات پرداخت حساس مستقیماً توسط درگاه بانکی پردازش می‌شوند.","کاربران می‌توانند درخواست‌های مرتبط با اطلاعات خود را از مسیر پشتیبانی ثبت کنند."].map(x=><p className="flex gap-3 rounded-xl bg-white p-4 text-[13px] leading-6" key={x}><span className="text-[#238a57]">✓</span>{x}</p>)}</div><p className="mt-5 text-[13px] text-[#60758a]">برای اطلاع از جزئیات بیشتر و بندهای قانونی، متن کامل این صفحه را مطالعه کنید.</p></div></section>
  <main className="mx-auto grid w-[1200px] grid-cols-[1fr_300px] gap-10 py-14"><article>{sections.map((s,i)=><section id={"section-"+(i+1)} className="mb-9 rounded-[18px] border border-[#e4ebf1] bg-white p-7 scroll-mt-5" key={s.title}><h2 className="mb-4 text-[20px] font-bold">{s.title}</h2>{s.intro&&<p className="text-[14px] leading-8 text-[#425b72]">{s.intro}</p>}{s.bullets&&<ul className="mt-4 space-y-3 text-[14px] leading-7 text-[#425b72]">{s.bullets.map(b=><li className="flex gap-3" key={b}><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#2094e3]"/>{b}</li>)}</ul>}{s.note&&<div className="mt-5 rounded-xl border-r-4 border-[#2094e3] bg-[#eaf5fd] p-4 text-[13px] leading-7 text-[#35536e]">{s.note}</div>}{i===7&&<div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-xl bg-[#e8f7ee] p-4"><b>اطلاعات عمومی</b><p className="mt-2 text-[12px] leading-6">نام پروژه، مکان اجرا، میزان پیشرفت، استارتاپ مجری و نتایج KPI</p></div><div className="rounded-xl bg-[#fef0ee] p-4"><b>اطلاعات محرمانه</b><p className="mt-2 text-[12px] leading-6">هویت کاربران، مدارک مالی تفصیلی، کد ملی و رزومه‌های خصوصی</p></div></div>}{i===13&&<table className="mt-5 w-full text-right text-[13px]"><thead><tr><th>نسخه</th><th>تاریخ اجرا</th><th>خلاصه تغییرات</th><th>مشاهده نسخه</th></tr></thead><tbody><tr><td>۲.۰</td><td>۱ شهریور ۱۴۰۵</td><td>به‌روزرسانی تعاریف KPI و فرآیند تأیید گواهی سازمانی</td><td>نسخه فعلی</td></tr><tr><td>۱.۰</td><td>۲۴ اسفند ۱۴۰۴</td><td>انتشار نسخه اولیه سیاست حریم خصوصی سامانه ماه</td><td>آرشیو</td></tr></tbody></table>}{i===14&&<div className="mt-5 flex gap-3"><button className="rounded-xl bg-[#2094e3] px-5 py-3 font-bold text-white">ثبت درخواست حریم خصوصی</button><button className="rounded-xl border border-[#2094e3] px-5 py-3 font-bold text-[#2094e3]">تماس با پشتیبانی</button></div>}</section>)}</article>
    <aside className="h-fit rounded-2xl border border-[#e4ebf1] bg-white p-6"><h2 className="mb-3 font-bold">فهرست مطالب سند</h2>{sections.map((s,i)=><a className="block border-b border-[#eef2f5] py-2.5 text-[12px] text-[#60758a]" href={"#section-"+(i+1)} key={s.title}>{s.title}</a>)}</aside></main><Footer/>
 </div>;}