import { Link } from "react-router-dom";
import "../../index.css";

const imgChatGptImage1 = "/assets/emdad/dashboard/logo.png";
const imgSuccessIcon = "/assets/emdad/article172-approvals/success/success-icon.svg";
const imgEllipse = "/assets/emdad/article172-approvals/success/process-step.svg";
const imgGroup = "/assets/emdad/dashboard/group.svg";
const imgGroup1 = "/assets/emdad/dashboard/group1.svg";
const imgCertificateIcon = "/assets/emdad/dashboard/certificate-icon.svg";
const imgFundSynergyIcon = "/assets/emdad/dashboard/fund-synergy-icon.svg";
const imgGroup2 = "/assets/emdad/dashboard/group2.svg";
const imgGroup3 = "/assets/emdad/dashboard/group3.svg";
const imgGroup4 = "/assets/emdad/dashboard/group4.svg";

export default function EmdadArticle172Success() {
  return (
    <div className="emdad-panel bg-[#f5f8fb] relative w-full h-full" data-node-id="2165:2" data-name="emdad-article172-success">
      <div className="absolute bg-[#f5f8fb] content-stretch flex flex-col gap-[16px] h-[900px] items-start left-0 overflow-clip px-[28px] py-[22px] top-0 w-[1216px]" data-node-id="2165:3" data-name="Main Content">
        <div className="bg-white border border-[#e4ebf1] border-solid h-[64px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2165:148" data-name="header">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[30px] justify-center leading-[0] left-[1131px] text-[#17324d] text-[22px] text-right top-[22px] w-[572px]" data-node-id="2165:149"><p className="leading-[normal]" dir="auto">تأیید نهایی ماده ۱۷۲ ثبت شد</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[12px] text-right top-[44px] w-[672px]" data-node-id="2165:150"><p className="leading-[normal]" dir="auto">درخواست شرکت تأیید شد و گواهی ماده ۱۷۲ در وضعیت صادرشده قرار گرفت.</p></div>
          <div className="absolute bg-[#eaf8f0] h-[30px] left-[19px] overflow-clip rounded-[15px] top-[16px] w-[122px]" data-node-id="2165:151" data-name="status"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[61px] text-[#159455] text-[12px] text-center top-[15px] w-[106px]" data-node-id="2165:152"><p className="leading-[normal]" dir="auto">صادر شده</p></div></div>
        </div>

        <div className="bg-[#eaf8f0] border border-[#bee5d0] border-solid h-[138px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2165:153" data-name="success-banner">
          <div className="absolute left-[1081px] size-[54px] top-[33px]" data-node-id="2165:154" data-name="success-icon"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgSuccessIcon} /></div>
          <div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[40px] justify-center leading-[0] left-[1108px] text-[28px] text-center text-white top-[59px] w-[38px]" data-node-id="2165:155"><p className="leading-[normal]">✓</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[1049px] text-[#17324d] text-[19px] text-right top-[38px] w-[660px]" data-node-id="2165:156"><p className="leading-[normal]" dir="auto">گواهی ماده ۱۷۲ صادر شد</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[42px] justify-center leading-[0] left-[1049px] text-[#60758a] text-[13px] text-right top-[80px] w-[840px]" data-node-id="2165:157"><p className="leading-[normal]" dir="auto">بررسی نهایی درخواست با موفقیت تکمیل شد و گواهی برای شرکت فعال شده است.</p></div>
          <div className="absolute bg-white h-[30px] left-[19px] overflow-clip rounded-[15px] top-[85px] w-[128px]" data-node-id="2165:158" data-name="active-pill"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[64px] text-[#159455] text-[12px] text-center top-[15px] w-[112px]" data-node-id="2165:159"><p className="leading-[normal]" dir="auto">گواهی فعال</p></div></div>
        </div>

        <div className="[word-break:break-word] bg-white border border-[#e4ebf1] border-solid h-[178px] leading-[0] overflow-clip relative rounded-[12px] shrink-0 text-right w-full" data-node-id="2165:160" data-name="certificate-summary">
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium justify-center left-[1131px] text-[#17324d] text-[18px] top-[27px] w-[372px]" data-node-id="2165:161"><p className="leading-[normal]" dir="auto">خلاصه گواهی صادرشده</p></div>
          <div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[18px] justify-center left-[1131px] text-[#60758a] text-[12px] top-[50px] w-[532px]" data-node-id="2165:162"><p className="leading-[normal]" dir="auto">​</p></div>
          <div className="absolute bg-[#f5f8fb] h-[52px] left-[809px] overflow-clip rounded-[8px] top-[69px] w-[350px]" data-node-id="2165:163" data-name="summary-cell"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[334px] text-[#60758a] text-[11px] top-[13px] w-[144px]" data-node-id="2165:164"><p className="leading-[normal]" dir="auto">نام شرکت</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[334px] text-[#17324d] text-[14px] top-[34px] w-[318px]" data-node-id="2165:165"><p className="leading-[normal]" dir="auto">پایدار پرداز خلاق آریا</p></div></div>
          <div className="absolute bg-[#f5f8fb] h-[52px] left-[435px] overflow-clip rounded-[8px] top-[69px] w-[350px]" data-node-id="2165:166" data-name="summary-cell"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[334px] text-[#60758a] text-[11px] top-[13px] w-[144px]" data-node-id="2165:167"><p className="leading-[normal]" dir="auto">پروژه</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[334px] text-[#17324d] text-[14px] top-[34px] w-[318px]" data-node-id="2165:168"><p className="leading-[normal]" dir="auto">سلامت خانواده</p></div></div>
          <div className="absolute bg-[#f5f8fb] h-[52px] left-[61px] overflow-clip rounded-[8px] top-[69px] w-[350px]" data-node-id="2165:169" data-name="summary-cell"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[334px] text-[#60758a] text-[11px] top-[13px] w-[144px]" data-node-id="2165:170"><p className="leading-[normal]" dir="auto">وضعیت گواهی</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[334px] text-[#159455] text-[14px] top-[34px] w-[318px]" data-node-id="2165:171"><p className="leading-[normal]" dir="auto">صادر شده</p></div></div>
          <div className="absolute bg-[#f5f8fb] h-[52px] left-[809px] overflow-clip rounded-[8px] top-[125px] w-[350px]" data-node-id="2165:172" data-name="summary-cell"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[334px] text-[#60758a] text-[11px] top-[13px] w-[144px]" data-node-id="2165:173"><p className="leading-[normal]" dir="auto">شماره گواهی</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[334px] text-[#17324d] text-[14px] top-[34px] w-[318px]" data-node-id="2165:174"><p className="leading-[normal]">—</p></div></div>
          <div className="absolute bg-[#f5f8fb] h-[52px] left-[435px] overflow-clip rounded-[8px] top-[125px] w-[350px]" data-node-id="2165:175" data-name="summary-cell"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[334px] text-[#60758a] text-[11px] top-[13px] w-[144px]" data-node-id="2165:176"><p className="leading-[normal]" dir="auto">تاریخ صدور</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[334px] text-[#17324d] text-[14px] top-[34px] w-[318px]" data-node-id="2165:177"><p className="leading-[normal]">—</p></div></div>
          <div className="absolute bg-[#f5f8fb] h-[52px] left-[61px] overflow-clip rounded-[8px] top-[125px] w-[350px]" data-node-id="2165:178" data-name="summary-cell"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[16px] justify-center left-[334px] text-[#60758a] text-[11px] top-[13px] w-[144px]" data-node-id="2165:179"><p className="leading-[normal]" dir="auto">مبلغ مورد تأیید</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[24px] justify-center left-[334px] text-[#17324d] text-[14px] top-[34px] w-[318px]" data-node-id="2165:180"><p className="leading-[normal]">—</p></div></div>
        </div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[184px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2165:181" data-name="process-state">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[1131px] text-[#17324d] text-[18px] text-right top-[27px] w-[312px]" data-node-id="2165:182"><p className="leading-[normal]" dir="auto">وضعیت فرایند صدور</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[12px] text-right top-[50px] w-[482px]" data-node-id="2165:183"><p className="leading-[normal]" dir="auto">​</p></div>
          {[{x:863,n:"۱",t:"ثبت پرداخت",d:"پرداخت مستقیم به حساب کمیته امداد ثبت شده",id:184},{x:583,n:"۲",t:"تطبیق اطلاعات",d:"اطلاعات حقوقی و مالیاتی شرکت بررسی شده",id:189},{x:303,n:"۳",t:"تأیید نهایی",d:"ضوابط قانونی توسط کمیته امداد تأیید شده",id:194},{x:23,n:"۴",t:"صدور گواهی",d:"گواهی برای شرکت فعال و قابل دریافت شده",id:199}].map((step) => (
            <div key={step.n} className="absolute bg-[#f5f8fb] h-[82px] overflow-clip rounded-[10px] top-[77px] w-[264px]" style={{left:step.x}} data-node-id={`2165:${step.id}`} data-name="process-step">
              <div className="absolute left-[208px] size-[36px] top-[14px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgEllipse} /></div>
              <div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium justify-center leading-[0] left-[226px] size-[24px] text-[13px] text-center text-white top-[31px]"><p className="leading-[normal]">{step.n}</p></div>
              <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[22px] justify-center leading-[0] left-[196px] text-[#17324d] text-[13px] text-right top-[23px] w-[176px]"><p className="leading-[normal]" dir="auto">{step.t}</p></div>
              <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[34px] justify-center leading-[0] left-[196px] text-[#60758a] text-[11px] text-right top-[55px] w-[176px]"><p className="leading-[normal]" dir="auto">{step.d}</p></div>
            </div>
          ))}
        </div>

        <div className="[word-break:break-word] bg-[#ebf6fd] border border-[#cae4f6] border-solid h-[86px] leading-[0] overflow-clip relative rounded-[12px] shrink-0 text-right w-full" data-node-id="2165:204" data-name="company-availability-note"><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-medium h-[26px] justify-center left-[1131px] text-[#17324d] text-[15px] top-[24px] w-[272px]" data-node-id="2165:205"><p className="leading-[normal]" dir="auto">دسترسی شرکت به گواهی</p></div><div className="-translate-x-full -translate-y-1/2 absolute flex flex-col font-sans font-normal h-[26px] justify-center left-[1131px] text-[#60758a] text-[12px] top-[52px] w-[972px]" data-node-id="2165:206"><p className="leading-[normal]" dir="auto">نسخه رسمی گواهی در بخش «گواهی ماده ۱۷۲» پنل شرکت در وضعیت صادرشده قرار می‌گیرد و از همان بخش قابل دریافت و بایگانی است.</p></div></div>

        <div className="bg-white border border-[#e4ebf1] border-solid h-[102px] overflow-clip relative rounded-[12px] shrink-0 w-full" data-node-id="2165:207" data-name="actions">
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[24px] justify-center leading-[0] left-[1131px] text-[#17324d] text-[15px] text-right top-[23px] w-[342px]" data-node-id="2165:208"><p className="leading-[normal]" dir="auto">پرونده این درخواست بسته شد</p></div>
          <div className="-translate-x-full -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-normal h-[20px] justify-center leading-[0] left-[1131px] text-[#60758a] text-[12px] text-right top-[47px] w-[652px]" data-node-id="2165:209"><p className="leading-[normal]" dir="auto">این درخواست از صف نیازمند بررسی خارج شده و نتیجه نهایی در سوابق گواهی‌ها ثبت می‌شود.</p></div>
          <Link to="/panel/emdad/article172-approvals" className="absolute bg-white block border border-[#e4ebf1] border-solid cursor-pointer h-[42px] left-[19px] overflow-clip rounded-[8px] top-[49px] w-[220px]" data-node-id="2165:210" data-name="back-to-article172-list"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[26px] justify-center leading-[0] left-[109px] text-[#17324d] text-[13px] text-center top-[20px] w-[200px]" data-node-id="2165:211"><p className="leading-[normal]" dir="auto">بازگشت به درخواست‌های ماده ۱۷۲</p></div></Link>
          <Link to="/panel/emdad" className="absolute bg-[#2094e3] block cursor-pointer h-[42px] left-[251px] overflow-clip rounded-[8px] top-[49px] w-[190px]" data-node-id="2165:212" data-name="back-to-dashboard"><div className="-translate-x-1/2 -translate-y-1/2 [word-break:break-word] absolute flex flex-col font-sans font-medium h-[26px] justify-center leading-[0] left-[95px] text-[13px] text-center text-white top-[21px] w-[170px]" data-node-id="2165:213"><p className="leading-[normal]" dir="auto">بازگشت به داشبورد</p></div></Link>
        </div>
      </div>

      <div className="absolute bg-[#17324d] content-stretch flex flex-col gap-[10px] h-[900px] items-end left-[1216px] pb-[18px] pt-[20px] px-[16px] top-0 w-[224px]" data-node-id="2165:86" data-name="colored-sidebar">
        <div className="bg-white content-stretch flex h-[56px] items-center justify-end overflow-clip px-[10px] py-[8px] relative rounded-[12px] shrink-0 w-[192px]" data-node-id="2165:87" data-name="brand-logo"><div className="h-[40px] relative shrink-0 w-[118px]" data-node-id="2165:88"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="" className="absolute h-full left-[5.28%] max-w-none top-0 w-[100.73%]" src={imgChatGptImage1} /></div></div></div>
        <div className="[word-break:break-word] content-stretch flex flex-col gap-[3px] h-[64px] items-start justify-end overflow-clip px-[8px] py-[7px] relative shrink-0 text-center w-[192px]" data-node-id="2165:89" data-name="panel-identity"><p className="font-sans font-medium h-[24px] leading-[normal] relative shrink-0 text-[13px] text-white w-[176px]" dir="auto" data-node-id="2165:90">سامانه ماه</p><div className="flex flex-col font-sans font-normal h-[18px] justify-center leading-[0] relative shrink-0 text-[#d8e7f3] text-[10px] w-[176px]" data-node-id="2165:91"><p className="leading-[normal]" dir="auto">پنل کمیته امداد</p></div></div>
        <Link to="/panel/emdad" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2165:92" data-name="dashboard-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2165:93">داشبورد</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[11.11%]"><div className="absolute inset-[-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup} /></div></div></div></div></Link>
        <Link to="/panel/emdad/release-requests" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2165:101" data-name="release-requests-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2165:102">درخواست‌های آزادسازی</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[22.22%_13.89%_19.44%_13.89%]"><div className="absolute inset-[-7.62%_-6.15%]"><img alt="" className="block max-w-none size-full" src={imgGroup1} /></div></div></div></div></Link>
        <Link to="/panel/emdad/article172-approvals" className="bg-[#2094e3] h-[38px] overflow-clip relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2165:108" data-name="article-172-approvals-nav"><p className="-translate-x-full [word-break:break-word] absolute font-sans font-normal leading-[normal] left-[152px] text-[12px] text-right text-white top-[9.5px] w-[142px]" dir="auto" data-node-id="2165:109">تأیید گواهی ماده ۱۷۲</p><div className="absolute left-[162px] size-[18px] top-[10px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgCertificateIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2223:56" data-name="fund-synergy-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2223:57">هم‌افزایی صندوق</p><div className="relative shrink-0 size-[18px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgFundSynergyIcon} /></div></Link>
        <Link to="/panel/emdad/fund-synergy/history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2237:211" data-name="fund-synergy-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2237:212">سوابق هم‌افزایی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/payment-history" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2165:114" data-name="payment-history-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2165:115">سوابق پرداخت</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <Link to="/panel/emdad/financial-reports" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2165:122" data-name="financial-reports-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2165:123">گزارش‌های مالی</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[13.89%_11.11%]"><div className="absolute inset-[-6.15%_-5.71%]"><img alt="" className="block max-w-none size-full" src={imgGroup3} /></div></div></div></div></Link>
        <Link to="/panel/emdad/fund-returns" className="content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end overflow-clip px-[12px] relative rounded-[10px] shrink-0 w-[192px]" data-node-id="2382:446" data-name="fund-returns-nav"><p className="[word-break:break-word] font-sans font-normal leading-[normal] opacity-90 relative shrink-0 text-[12px] text-right text-white w-[142px]" dir="auto" data-node-id="2382:447">منابع برگشتی صندوق</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[27.78%_19.44%_22.22%_16.67%]"><div className="absolute inset-[-8.89%_-6.96%]"><img alt="" className="block max-w-none size-full" src={imgGroup2} /></div></div></div></div></Link>
        <div className="flex-[1_0_0] min-h-px relative w-[192px]" data-node-id="2165:139" data-name="sidebar-spacer" />
        <button type="button" className="bg-white content-stretch cursor-pointer flex gap-[10px] h-[38px] items-center justify-end opacity-96 overflow-clip px-[12px] relative rounded-[9px] shrink-0 w-[192px]" data-node-id="2165:140" data-name="logout-nav"><p className="[word-break:break-word] font-sans font-medium leading-[normal] relative shrink-0 text-[#17324d] text-[12px] text-right w-[142px]" dir="auto" data-node-id="2165:141">خروج از سیستم</p><div className="overflow-clip relative shrink-0 size-[18px]"><div className="absolute left-0 overflow-clip size-[18px] top-0"><div className="absolute inset-[16.67%_11.11%_16.67%_19.44%]"><div className="absolute inset-[-6.67%_-6.4%]"><img alt="" className="block max-w-none size-full" src={imgGroup4} /></div></div></div></div></button>
      </div>
    </div>
  );
}
